### ISSUE TITLE
2.0.8.1b: 0xC0000005 exception after writing to file via usvfs_x64 with xEdit

### ISSUE THREAD

**Issue by fireundubh** [LePresidente/modorganizer#10]
### Steps to Reproduce

1. Launch xEdit through MO.
2. Load `Fallout4.esm`.
3. Copy any record as an override to a new plugin.
4. Close xEdit and save the new plugin.
5. Attempt to relaunch xEdit through MO.

### Alternative Steps to Reproduce

1. Launch xEdit through MO.
2. Load a non-MO plugin.
3. Change the plugin in any way.
4. Close xEdit and save the changes.
5. Attempt to relaunch xEdit through MO.

### Result

MO crashes with the following exception:

> Exception Code: 0xC0000005
> Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

Loading plugins, and not writing new plugins or changes to existing plugins, does not crash MO.

### Attachment

[0xC0000005.dmp.zip](https://github.com/LePresidente/modorganizer/files/673923/0xC0000005.zip)

**Comment by fireundubh** [comment]
This issue occurs with other games.

**Comment by derossm** [comment]
If you attempt to launch anything through MO2 after doing anything in xEdit that involves creating a new file or moving a file, it seems to cause a crash in my experience. There is also an error when you close MO2 instead of trying to launch something. I always close MO2 after using xEdit before trying to run the game to be safe, but I haven't noticed exactly what situations cause it to not produce the stopped working message.

Unfortunately, 0xC...5 is a useless exception, since it just means memory outside the allocated address i.e. just about any memory related bug. The core dump should be more illuminating, especially with the source available. I will look at it this weekend and see if I have any ideas.

**Comment by joseph-crowell** [comment]
Maybe an issue due to improper cleanup/releasing file handles on the last xEdit thread.

**Comment by MaxwellLane** [comment]
Based on my testing, it's not just a xEdit issue. I can get the crash happens with any 32-bit program that modifies the virtual directory.

**Comment by Hugues92** [comment]
I tracked the issue in my test setup to (at least) when a 32 bit application modifies the context trees by allocating new nodes. As long as the 32 bit process is active, the memory it allocated for new nodes is valid. But once the process ends, access to that memory is no longer possible.
Crash occurs when calling context->redirectionTable()->clear(); (usvfs.cpp) from ClearVirtualMappings (usvfsconnector.cpp) the first time after the 32 bit process has returned control to modOrganizer.

To solve the issue it might be required that the actual memory allocation be done by the parent process and not the child spawn from it to run the tool.

Possibly freeing some nodes in the 32 bit process could have the same effect, I just haven't tested it yet.

**Comment by LePresidente** [comment]
Can't reproduce in 2.1.0

**Comment by Hugues92** [comment]
I crash on my Windows 10 1607 dev and test machine whenever I try to use the last USVFS (32 or 64). I'll try to test on other Windows 10 1709 later today. Using the previous version (from 2.0.8.3) over 2.1 it does generates the exception same as before.
On the one Windows 7 machine I tested the full 2.1, I get another type of crash from Windows when launching xEdit from MO but xEdit itself seems to be working and can do the test case without MO crashing. I am definitivly not confident this Windows 7 machine is a good machine for testing anyway.

**Comment by Hugues92** [comment]
So I also cannot reproduce the issue with 2.1.0 on my Windows 10 1709 gaming workstation (where the game is installed normally through steam and not simulated like on the two previous machines I tested).
So if we now can create or modify files with 32 bits programs launched from the 64 bit MO2 that is a huge progress :)
