### ISSUE TITLE
Wyre Bash fails to Luanch in Win 10

### ISSUE THREAD

**Issue by Helidoc65** [LePresidente/modorganizer#100]
Using Win 10 insider ver 16288 which has all the fixes for the 4GB limit and MO and is being rub on both fast and slow rings currently. In MO2 Wyre Bash fails to launch in this build but will launch in MO and in stand alone mode. I posted here [http://forum.step-project.com/topic/12553-wrye-bash-with-mo2-failure-to-launch-win-10-insiders/](url) to include my logs from WB and MO2.

**Comment by TucoPacifico1980** [comment]
Hello Helidoc65. So with Windows 16299.15 the problem still persists. I am afraid, in a couple of days a big part of TUCOGUIDE users will be forced to go python...

**Comment by Silarn** [comment]
@LePresidente has modified the WryeBash code to allow for a new startup argument which bypasses the UAC conflict preventing MO2 from running WryeBash. You can find his version on the Discord channel. Maybe the official release can include this change.

**Comment by Silarn** [comment]
@LePresidente has mostly fixed this issue in our development builds, though there is ongoing work.

**Comment by TucoPacifico1980** [comment]
@Silarn, could you direct me to the Discord channel,  thanks

**Comment by Silarn** [comment]
It's on the GitHub description

**Comment by Silarn** [comment]
While improvements to USVFS are ongoing, the latest dev builds should work for most recent builds of Wrye Bash. Closing this ticket.
