### ISSUE TITLE
Downloads consistently fail after retarting multiple times

### ISSUE THREAD

**Issue by Taje01taje** [LePresidente/modorganizer#101]
No matter what I try to download the download restarts after getting a bit through the install, then shortly just fails the download, then gives an unknown error message.
[log](https://pastebin.com/05d1QG3e)
[internet speed](http://beta.speedtest.net/result/6661343168)

**Comment by Silarn** [comment]
This may be related to the memory bug.

**Comment by Silarn** [comment]
Can you replicate this issue with the latest builds? I'm going to close this if there's no response in the next several days.
