### ISSUE TITLE
Game plugins aren't included in the vfs when MO2 launches FO4

### ISSUE THREAD

**Issue by wyrde** [LePresidente/modorganizer#105]
Windows 7, FO4 1.10.26.0.1 
MO2 2.0.8.3 revision C64E12A
GetF4SEVersion returns F4SE version: 0.6.0, release idx 7, runtime 010A01A0

When starting the game, no plugin files (esp, esm, esl) are included in the vfs. BSAs and loose files are. When starting other applications, the plugins are included and usable normally. I can see them and edit them with wrye bash, fo4edit, merge plugins, etc.

Attached are usvfs logs for running FO4 with and without F4SE and one with bash.

[fo4 f4se usvfs-2017-10-22_14-16-21.log](https://github.com/LePresidente/modorganizer/files/1404999/fo4.f4se.usvfs-2017-10-22_14-16-21.log)
[fo4 f4se usvfs-2017-10-22_14-43-12.log](https://github.com/LePresidente/modorganizer/files/1405000/fo4.f4se.usvfs-2017-10-22_14-43-12.log)
[fo4 no-f4se usvfs-2017-10-22_14-52-06.log](https://github.com/LePresidente/modorganizer/files/1405001/fo4.no-f4se.usvfs-2017-10-22_14-52-06.log)
[using bash usvfs-2017-10-22_14-36-39.log](https://github.com/LePresidente/modorganizer/files/1405002/loading.bash.usvfs-2017-10-22_14-36-39.log)

This is with a fresh install of 2.0.8.3 in portable mode, but it happens with a standard install as well. (I switched to portable to localize as many files as possible.)

The issues noted in https://github.com/LePresidente/modorganizer/issues/88 and https://github.com/LePresidente/modorganizer/issues/82 don't seem to be occurring in this case. Somewhat the opposite.

Every other part of the modding process works normally (or, at least, well enough). Installing and packaging mods, cleaning and editing with xEdit, etc. The game loads textures, sounds, models fine. For example, the pip-pad works normally (including map and icon replacers) except there's no plugin to remove the pip-boy from the arm. F4SE runs and responds to console commands. Etc etc.

OMG this drove me nuts figuring out what was happening.

**Comment by LePresidente** [comment]
Join the discord channel please and test the latest tester release.

**Comment by Silarn** [comment]
There's a good chance this was fixed with my changes yesterday. LePresidente will have to build a new test release since there are a number of affected components.

**Comment by Silarn** [comment]
I'm closing this ticket due to inactivity. This problem is likely fixed on current builds.
