### ISSUE TITLE
Enhanced Character Edit additional sliders not showing

### ISSUE THREAD

**Issue by SquirrelFu** [LePresidente/modorganizer#109]
Exactly what the title says. For some reason, even though SKSE64 is used for the launch the game fails to employ the additional sliders from ECE. No error messages are thrown via message box.

**Comment by Silarn** [comment]
Does this mod require any special dll loader (skse64 or otherwise) for full functionality?

**Comment by SquirrelFu** [comment]
It requires SKSE64, but it doens't require the plugin preloader. Apparently an exe fix that was posted in the Discord fixed it.

**Comment by Silarn** [comment]
Based on conversions on discord a solution had been found in combination with recent development builds. Marking fixed.
