### ISSUE TITLE
MO no longer starts SSE and load order is screwed up by MO

### ISSUE THREAD

**Issue by Jokelly85** [LePresidente/modorganizer#110]
Thanks in advance.   This is the log for the crash..

[usvfs-2017-10-27_02-46-01.log](https://github.com/LePresidente/modorganizer/files/1420648/usvfs-2017-10-27_02-46-01.log)

**Comment by Silarn** [comment]
I assume you are still using 2.0.8.3b?

Are you using SKSE? This appears to be related to the handle leak issue, however we typically only see issues with this when running through SKSE.

If this is the case, these issues have been largely resolved by recent development. If possible, grab the latest build from the discord server and see how it works.

**Comment by Jokelly85** [comment]
sorry it took so long to respond, life has a way of getting in the way.  Thanks that seems to have been the problem.  I appreciate the help.
