### ISSUE TITLE
Crash when launching SKSE64

### ISSUE THREAD

**Issue by ExE-Boss** [LePresidente/modorganizer#112]
The dump file: [ModOrganizer.exe.dmp.zip](https://github.com/LePresidente/modorganizer/files/1422900/ModOrganizer.exe.dmp.zip)

## Steps which resulted in this:
1. Start MO
2. Use MO to start LOOT
3. Sort mod list
4. Use MO to start SSEEdit
5. Clean DLCs
6. Move DLC files from Overwrite to a new mod folder and then to “%SkyrimSpecialEditionInstallDirectory%/Data/”
7. Start SKSE64
8. MO crashed

**Comment by Silarn** [comment]
Are you using version 2.0.8.3b? If so then this is probably a known bug and fixed in 2.1, which is under active development.

**Comment by ExE-Boss** [comment]
Yes, I’m using 2.0.8.3b.

**Comment by Silarn** [comment]
This is almost definitely the memory / handle issue plaguing 2.0.8.3b. These issues have been largely resolved. If you can grab the development build from the discord server, please give that a try and see if it resolves your problems.

**Comment by Silarn** [comment]
This issue is resolved in development builds.
