### ISSUE TITLE
Forced Antialiasing from Nvidia Control Panel doesn't work with 2.1

### ISSUE THREAD

**Issue by Shizof** [LePresidente/modorganizer#115]
I had opened this issue for Helidoc's fork but it exists in 2.1 too.
In 2.0.8.3b build, when I turn off TAA from ini files but override it from Nvidia Control Panel Antialiasing settings for better visuals, it works. I get superior antialiasing.
But in 2.1 builds, this method doesn't work.

bUseTAA=0 settings are identical, both zero.

Also I copied 2.0.8.3b ini files to 2.1 before testing, and it changes the following values automatically after running the game. 
May be the reason:

Automatically added and 2 changed settings in skyrimprefs.ini:

```
[Controls]
fGamepadHeadingSensitivity=0.6667
bAlwaysRunByDefault=1
bInvertYValues=0
bGamePadRumble=1
bUseKinect=0

[Display]
bEnableImprovedSnow=0  ---> Changed setting(was 1)
bIBLFEnable=0 ---> Changed setting(was 1)
iNumSplits=2
uBookRatio=2
bForceCreateTarget=0
iReflectionResolutionDivider=2
iSaveGameScreenShotHeighWSt=192
iSaveGameScreenShotWidthWS=320
iSaveGameScreenShotHeight=192
iSaveGameScreenShotWidth=256
bBorderless=0
iScreenShotIndex=0

[General]
iStoryManagerLoggingEvent=-1
bEnableStoryManagerLogging=0

[Interface]
bShowCompass=1

[MAIN]
bGamepadEnable=0
bCrosshairEnabled=1
fHUDOpacity=1.0000
bSaveOnPause=0
bSaveOnTravel=1
bSaveOnWait=1
bSaveOnRest=1

[TerrainManager]
bShowLODInEditor=1

[Bethesda.net]
uPersistentUuidData3=3576533843
uPersistentUuidData2=2503049662
uPersistentUuidData1=3549645857
uPersistentUuidData0=2092868926
[GamePlay]
bShowFloatingQuestMarkers=1
bShowQuestMarkers=1
iDifficulty=2
[SaveGame]
fAutosaveEveryXMins=15.0000
[AudioMenu]
fAudioMasterVolume=1.0000
fVal7=1.0000
uID7=959775
fVal6=1.0000
uID6=922759976
fVal5=0.8000
uID5=554685
fVal4=0.8000
uID4=1007612
fVal3=1.0000
uID3=106685
fVal2=1.0000
uID2=410705
fVal1=1.0000
uID1=522251
fVal0=1.0000
uID0=94881
[NavMesh]
fObstacleAlpha=0.5000
fCoverSideHighAlpha=0.8000
fCoverSideLowAlpha=0.6500
fEdgeFullAlpha=1.0000
fEdgeHighAlpha=0.7500
fEdgeLowAlpha=0.5000
fTriangleFullAlpha=0.7000
fTriangleHighAlpha=0.3500
fTriangleLowAlpha=0.2000
fLedgeBoxHalfHeight=25.0000
fEdgeDistFromVert=10.0000
fEdgeThickness=10.0000
fPointSize=2.5000
```

other changes are only .0000 in some values.

**Comment by Silarn** [comment]
I believe this could be due to the handle issues which are being worked on. Does this problem still affect the latest builds?

**Comment by Shizof** [comment]
Yes. 30.10.2017 build has this issue.

**Comment by Shizof** [comment]
Did some tests. Turns out 2.0.8.3b uses ini files from "my documents/my games/skyrim special edition" folder. I had taa enabled there, but not in profile ini configurations. 2.0.8.3b was using wrong ini files and 2.1 was using the right ini files. So Nvidia Control Panel anti-aliasing override was never working.
