### ISSUE TITLE
Enhancement to make sorting left pane easier.

### ISSUE THREAD

**Issue by cfs3rd** [LePresidente/modorganizer#116]
FYI...Using the latest test build from Discord. 
It would be nice if when a mod is selected in the left pane all related plugins in the right pane are highlighted or when a plugin is selected in the right pane it's related mod is highlighted in the left pane. This would make sorting the left pane waaaay easier.
Thanks, cfs111

**Comment by Silarn** [comment]
This is something I've wanted myself, so I'll see if I can find time to add it. There are other, deeper bugs we're still working through to stabilize MO2, so those will take priority.

**Comment by cfs3rd** [comment]
Thanks, no rush on this. Get MO2 right first. Just always thought this feature would be great. I posted this on Tannin's original MO2 GitHub but about a week later it was announced that he went to Nexus to work. If you missed it I am cfs111 on Discord, so any specific testing I can do to help just message me.

**Comment by Silarn** [comment]
This has been completed in development.
