### ISSUE TITLE
MO 2.1 release 2017-11-10 not working with Windows 7 64-bit as release 2017-11-04 did.

### ISSUE THREAD

**Issue by joelima1310** [LePresidente/modorganizer#127]
System is reporting this fatal error message when starting ModOrganizer.exe on a Windows 7 64-bit rig: "The procedure entry point CopyFile2 could not be located in the dynamic link library KERNEL32.dll." exclusively for the above mentioned release (2017-11-10). Using 2.0.8.3 installation as a base and overwriting it with the 2017-11-04 release files, made it starts normally.  This issue was already discussed in the Discord's #testers channel and LePresidente is aware of it. Posted here just for following up.

**Comment by Silarn** [comment]
Hooks were added for these functions as they are used by Wrye Bash. However, these methods were only added as of Windows 8. My best guess is Python is dynamically detecting the OS version and calling these functions if available. Anyway, these functions are now loaded dynamically from the DLLs when present which should prevent linking issues at runtime and will only hook the functions on Windows 8 and newer.

Closing the ticket.
