### ISSUE TITLE
What version of Microsoft.net does Mod Organizer 2 support?

### ISSUE THREAD

**Issue by Mikey7979** [LePresidente/modorganizer#128]
I just installed Microsoft.net ver 4.7 and I have a message in my overwrite folder that says that "dotnet is not installed or is outdated." If I click on the message and highlight it in blue, a web link appears at the bottom of the overwrite window and states that I can get the file from here http://www.microsoft.com/en-us/download/details.aspx?id=17851. I go to the Microsoft page and download the software and then try to install software (as administrator) I get the following nastygram:

Microsoft .NET Framework 4 is already a part of this operating system.  You do not need to install the .NET Framework 4 redistributable. <A HREF="http://go.microsoft.com/fwlink/?LinkId=164207">More information</A>. 

Same or higher version of .NET Framework 4 has already been installed on this computer.

I am using windows 10 and I installed Mod Organizer 2 version 2.0.8.3b from the Nexus SkrimSE page.

**Comment by Shirozawa** [comment]
You just have to install .NET Framework 3.5.

Just follow this guide : https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10

It worked for me :)

**Comment by Mikey7979** [comment]
Thank you. This was a new computer and I had just installed Windows 10, so I am not sure it was a bad install or if 3.5 is just not installed/enabled this point. Also another issue that seemed to be driving Mod Organizer mad was an error with regards to a missing msvcr100.dll, it looks like my release of windows 10 is renaming this file to msvcr100_clr0400.dll. I made a copy of this .dll and renamed it back to the old msvcr100.dll name and that made Mod Organizer 2 very happy. You may want to put a small note in the instructions somewhere to assist others because these two issues have also resolved my LOOT and my FINIS issues as well. Mod Organizer 2 still crashes on a regular basis, but I can live with that at this point. Again thanks for your help.

**Comment by Silarn** [comment]
To be honest this warning isn't even accurate anymore. The latest builds of NCC require .NET 4.6. So this check needs updating.

**Comment by Silarn** [comment]
I've updated this check in the latest builds and am going to close this ticket.
