### ISSUE TITLE
Mod Configuration Menu (MCM) not working unless you place stuff into real Data/MCM

### ISSUE THREAD

**Issue by blubberdiblub** [LePresidente/modorganizer#129]
I'm testing with Fallout 4.
I'm using the MO2 2.1 build from 2017-11-10.
I also use the updated python boost dll and the usvfs dlls that were posted to #testers on Discord on 2017-11-11.
System is Windows 10 (Build 16299).

The starting point is both the current Mod Configuration Menu as well as the MCM Demo plugin installed - each as separate Mod in the MO2 list and both activated and no files removed from them in any of the following cases.

Furthermore, the overwrite directory is empty (i. e. contains no `MCM\Config` directory or the like).

Basically one of 3 observations arise, depending on what I put into the real Data folder of Fallout 4:

- **`[A]`** No entry for "Mod Config" at all appears in the pause menu.
- **`[B]`** The entry for "Mod Config" does appear in the pause menu, but the MCM menu lists no entries at all, not even "MCM Settings" or "Hotkey Manager" that both come with MCM.
- **`[C]`** The entry in the pause menu exists and the MCM menu lists all expected entries: "MCM Settings", "Hotkey Manager" and the plugin's "MCM Demo".

I also had a fourth case during testing related to the Settings directory that mixed it all up, where all except the plugin's entry appeared, but I cannot reproduce that. I'm not sure whether I did something wrong or there's some kind of mandelbug in the mix.

Directory or File | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19
--- | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | - | -
Data\MCM | ⬜️ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
Data\MCM\Settings | ⬜️ | ⬜️ | ✅ | ✅ | ⬜️ | ✅ | ✅ | ⬜️ | ✅ | ✅ | ⬜️ | ✅ | ✅ | ⬜️ | ✅ | ✅ | ⬜️ | ✅ | ✅
Data\MCM\Settings\readme.txt | ⬜️ | ⬜️ | ⬜️ | ✅ | ⬜️ | ⬜️ | ✅ | ⬜️ | ⬜️ | ✅ | ⬜️ | ⬜️ | ✅ | ⬜️ | ⬜️ | ✅ | ⬜️ | ⬜️ | ✅
Data\MCM\Config | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
Data\MCM\Config\MCM | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️
Data\MCM\Config\MCM\settings.ini | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ✅ | ✅ | ✅ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️
Data\MCM\Config\MCM_Demo | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅
Data\MCM\Config\MCM_Demo\config.json | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ⬜️ | ✅ | ✅ | ✅
**Outcome** | **A** | **A** | **A** | **A** | **B** | **B** | **B** | **B** | **B** | **B** | **B** | **B** | **B** | **B** | **B** | **B** | **C** | **C** | **C**

What that means is the existence of directory `Data\MCM` doesn't help at all.
However, the existence of directory `Data\MCM\Config` makes at least the _MCM Config_ appear in the pause menu, albeit with an empty list in its own menu.
Only the `config.json` of the MCM plugins under `Data\MCM\Config\Plugin_Name\config.json` makes everything appear as desired.

Modulo the case with only the built-in entries being available which I wasn't able to reproduce.

**Comment by blubberdiblub** [comment]
Here is the `usvfs.log` from the first case. (I can also provide the log files from the other cases if needed.)

[usvfs-00000000.log](https://github.com/LePresidente/modorganizer/files/1464669/usvfs-00000000.log)

Don't mind the funny name suffix - it was just my way to organize them.

**Comment by wyrde** [comment]
I noticed when looking through my own usvfs log that some of the files in the mcm tree were being included in the vfs but not the .json files. 

I decided to take a closer look and did the thing where I start a cmd window which in turn runs f4se_loader and starts FO4. I can wandered through the data\mcm tree and all the files are there. But if I look in the usvfs log, none of the .json files show up. Most of the ini files are in the log, but not all of them.

In the case of XDI, data\MCM\Config\XDI seems to be created, but it's not populated.

(I underlined in red for each file I found)
![image](https://user-images.githubusercontent.com/9657443/32705341-23dd585a-c7e1-11e7-8163-50c9c4fd7be3.png)

I'm not sure if cmd.exe is getting the usvfs differently than FO4, but thought this was pretty strange.

PS: the thing (tm) https://pc.reddit.com/r/skyrimmods/comments/76yqm8/mo2_acts_really_odd_after_running_a_game/dohomez/

**Comment by Silarn** [comment]
Latest USVFS builds have addressed some of these issues. With the final changes for WryeBash, it's possible it works as expected now but it should with with just the config and settings directories created now.

**Comment by Silarn** [comment]
Until we can identify the 'nested directory' bug, you will have to create the basic directory structure for this (and possibly other) mods that search for files in nested directories.

In the case of MCM, adding MCM\Settings and MCM\Config should allow all MCM mods to work as expected without putting any actual files in the Data directory.

**Comment by Silarn** [comment]
LePresidente's latest USVFS change should fix any subdirectory search patterns. Closing this.
