### ISSUE TITLE
I can not start SSE though MO

### ISSUE THREAD

**Issue by Uisca** [LePresidente/modorganizer#13]
I can not start sse though MO no matter if i go start for the game or the launcher i get and i get a steam error every time
application load error 3:0000065432

 I can not fix it for things i have already tryed look here
http://forum.step-project.com/topic/11720-can-not-launch-sse-though-mo/

**Comment by ZachHaber** [comment]
Are you using the 2.0.8b release?
Also, are you running it in the skyrim special edition mode? (what little I saw in your .ini file made me wonder).
Could you attach that here so I can view them? (I don't have an account with STEP)

**Comment by Uisca** [comment]
here are the files you asked for
[Files.zip](https://github.com/LePresidente/modorganizer/files/675549/Files.zip)

**Comment by ZachHaber** [comment]
Are you running MO2 as an admin, as you might need to based on where your directory is.

**Comment by Uisca** [comment]
yes its set to always run as admin

**Comment by Uisca** [comment]
Hello can anyone help with this

**Comment by ShadowySchemer** [comment]
See if this helps you at all: [https://github.com/LePresidente/modorganizer/issues/67](url)
