### ISSUE TITLE
F4SE (1.10.40 - build: 0.6.1) not loading in Mod organizer 2.1

### ISSUE THREAD

**Issue by Just-a-Fluke** [LePresidente/modorganizer#130]
F4SE is not starting when running the latest version of MO2.  Can start Fallout4.exe and the Fallout launcher through MO without any problems.

Have grabbed the latest usvfs.dll's from the discord

[Logs.zip](https://github.com/LePresidente/modorganizer/files/1485582/Logs.zip)

**Comment by Silarn** [comment]
Please try the latest builds. The only problems I've seen recently are related to long directory paths, antivirus software, and the Spring Creators Update version of Windows 10. (It is fixed with the Fall update.)
