### ISSUE TITLE
Mods are not being loaded when games are launched through shortcuts

### ISSUE THREAD

**Issue by oabdellatif** [LePresidente/modorganizer#131]
This is with the 11/10 MO 2.1 and 11/15 usvfs builds, although this issue does not seem to specific to either one.

When launching SSE through MO, selected mods are loaded as expected. However, when launching the game from a shortcut created through MO, none of the selected mods are loaded. This seems to be a longstanding bug in MO 2, as evidenced by issues TanninOne/modorganizer#425 and TanninOne/modorganizer#871.

**Comment by Silarn** [comment]
Shortcuts are created based on the current configuration. If that configuration changes the shortcuts likely need to be updated. But perhaps we can move to a WINE-like shortcut system that simply references the MO shortcut and launches it by proxy.

**Comment by oabdellatif** [comment]
It doesn't seem like the current configuration is being read properly, as shortcuts aren't working for me regardless of whether they've been recently or previously created. I figured a similar system was already in place though, as shortcuts simply reference the MO binary and specify which profile to load.

**Comment by Silarn** [comment]
Not sure if it was a different person, but on discord someone else resolved this by removing an old copy of MO. The shortcut was starting the wrong version.

**Comment by Silarn** [comment]
Recent changes should resolve this problem.
