### ISSUE TITLE
Links in quick access are lost after running WB through MO2 2.1 latest buid (12/10/2017 erasmux)

### ISSUE THREAD

**Issue by EsOmEs** [LePresidente/modorganizer#141]
# The problem

After running Wrye Bash through ModOrganizer 2 Version 2.1beta build from 12/10/2017, all quick access links in explorer are gone. Does not happen when WB is run outside of MO.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1beta build from 12/10/2017
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.0.8.3b
* Desktop OS/version used to run Mod Organizer: Windows 10 x64 Build xxx.1709

# Details

See above

# Link to Mod Organizer logs

**Comment by Squirrelydood** [comment]
Can confirm this issue. OS is Win10 and running Wrye Bash causes the quick access links in the windows side panel to be deleted as the program is launched.

**Comment by Silarn** [comment]
I've heard that the latest Wrye Bash beta release avoids this problem - but it still needs to be investigated.

Unfortunately, it's going to be on the backburner for a while as our limited dev resources work on other issues.

**Comment by Al12rs** [comment]
People have reported that this does not happen anymore with usvfs 0.31 beta5 available on discord. Please report if the issue continueas to reproduce while using them.

**Comment by EsOmEs** [comment]
Does not happen with latest discord release and usvfs build from there (usvfs 0.3b5 fixes that).
