### ISSUE TITLE
Enhancement Add option to clear Overwrite

### ISSUE THREAD

**Issue by cfs3rd** [LePresidente/modorganizer#149]
When overwrite is right clicked add an option to delete the contents, rather than having to choose Information then delete the contents.
Thanks, cfs111

**Comment by erasmux** [comment]
Should be fixed in the 26/12 dev build on the discord channel. Please test.

**Comment by cfs3rd** [comment]
Nice, works fine on 12/26 erasmux build. Thanks!!
