### ISSUE TITLE
2.0.8.1: "Download With Manager" function for FalloutNV not working

### ISSUE THREAD

**Issue by Maddremor** [LePresidente/modorganizer#15]
When attempting to download a file using the "Download With Manager" link on NexusMods for Fallout New Vegas, the download quickly reaches 100%, then is paused with the error message 
"Server replied: requested range not satisfiable (299)"
Manual downloads work fine.
This does not affect my instances of SkyrimSE and Fallout4 (have not checked F3, Oblivion or Oldrim).

Newbie speculation: Can this be related to 61edeb12f10707a03aea33e67ea6fd47990ee543?

**Comment by fireundubh** [comment]
Confirming that this issue occurs with FNV and does not occur with SSE or FO4.

**Comment by LePresidente** [comment]
The nexus mods page was changed by the looks of things, 

http://www.nexusmods.com/newvegas

**Comment by LePresidente** [comment]
This was fixed in 2.0.8.2b can you  verify?

**Comment by fireundubh** [comment]
Verified fixed.
