### ISSUE TITLE
Mods using a C# script in their FOMOD silently fail to install.

### ISSUE THREAD

**Issue by Evolution0** [LePresidente/modorganizer#151]
# The problem

Some mods using a C# script in their fomod fail to install at all.

# Environment

* Mod Organizer Version that exhibits the issue: 2.0.8.3
* Last Mod Organizer Version that did not exhibit the issue (if applicable): **See details below**.
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro x64

# Details

I haven't worked my way back from the latest to figure out the last version that didn't have this issue as I originally ran into it using 2.0.8.3 for managing Fallout: New Vegas, at that time I simply decided to use what I knew worked for a fact and is stable with F: NV - the last version of the original MO 1.3.11. 

I do know that there *is* a version of MO2 that works correctly as I used it before without issue (Only timeframe I have is pre-Skyrim: SE)

However I decided to use the latest version with Fallout 4 only to run into the issue again, a good way to reproduce it is attempt to install [NewDialog](https://www.nexusmods.com/fallout4/mods/619/) which uses a C# script.

This is not a game-breaker by any means, one can simply look through the C# script to get the paths of where certain files should go and manually create a mod via overwrite.

# Link to Mod Organizer logs

## MO Interface
```
10:09:47 [D] nexus category id 37 not mapped
10:09:47 [D] mod id guessed: Configurable New Dialog English ver0.7 - with DLC-619-0-7.7z -> 619
10:09:47 [D] using mod name "NewDialog" (id 619) -> Configurable New Dialog English ver0.7 - with DLC-619-0-7.7z
```
^ It just stops there, never says `module name: "blah blah"` or `"Installation Successful!"`, MO doesn't crash or hang something just seems to quietly fail in the background. I can continue to install other mods just fine.

**Comment by Evolution0** [comment]
Ah damn it, I thought I had seen an issue related to this but couldn't find it, turns out it was closed.

I can confirm that the latest build on discord does not have this issue.

**Comment by Silarn** [comment]
Thanks!
