### ISSUE TITLE
Creating an empty mod does not refresh the mod list

### ISSUE THREAD

**Issue by Evolution0** [LePresidente/modorganizer#152]
# The problem

When creating an empty mod there is no indication that it was successful and this may lead to users believing it does not work, you have to manually refresh the mod list for the empty mod to display. (Alternatively restarting MO2 does this.)

# Environment

* Mod Organizer Version that exhibits the issue: 2.0.8.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro x64

**Comment by Silarn** [comment]
I've seen this issue. Should be a fairly quick fix.

**Comment by Silarn** [comment]
Please verify the fix or I will close the issue within the next week or so.

**Comment by Nicz14** [comment]
Tried it, it refreshes now after creating an empty mod.

**Comment by Silarn** [comment]
Thanks! Closing as fixed.
