### ISSUE TITLE
local saves don't work

### ISSUE THREAD

**Issue by simpson409** [LePresidente/modorganizer#153]
# The problem

skyrim se won't save to "Mod Organizer 2\profiles\Default\saves" and can't read from it. the local saves are visible in the right hand saves tab, but not accessible in game.
and yes, of course i have the local savegame option checked.

# Environment

* Mod Organizer Version that exhibits the issue: Mod Organizer 2_0_8_3b
* Desktop OS/version used to run Mod Organizer: Windows 10 64 bit

**Comment by Silarn** [comment]
This issue should no longer be present in development builds on discord.

**Comment by Yoosk** [comment]
Issue is no longer present in latest dev builds, can close this one.

**Comment by simpson409** [comment]
i'm sorry at the time posting this i wasn't aware of the dev builds, i just assumed the one on the nexus was the most recent build.

**Comment by Silarn** [comment]
Thanks
