### ISSUE TITLE
Hidden console peeks on new output

### ISSUE THREAD

**Issue by FerusGrim** [LePresidente/modorganizer#155]
# The problem

When you're installing or enabling a plugin (or, presumably, whenever anything is logged), if you've hidden the console (dragged it down until it disappears), it briefly pops back up into view.

# Environment

Silarn Build (15/12/2017) Discord#builds (Message Snowflake: 391344924907405324)

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/FerusGrim/951a1871b3bac50cf835a27f62e1057c

## MO Interface

https://gist.github.com/FerusGrim/a75e3f0422dab7549db38e722efc7c75

**Comment by erasmux** [comment]
Doesn't seem to be reproducible in the latest builds, I think we can close it.
