### ISSUE TITLE
DSR missing masters Skyrim.esm and Update.esm

### ISSUE THREAD

**Issue by simpson409** [LePresidente/modorganizer#158]
# The problem
whenever i run the Dual Sheath Redux Patch through mod organizer it crashes with the message:
skyproc.exceptions.MissingMasters:
Dual Sheath Redux.esp has some missing masters:
- Skyrim.esm
- Update.esm

Please activate and try again.

DSR used to work in older versions of MO, 1.3 is the last version i had before upgrading to MO2 and it worked fine.
# Environment

* Mod Organizer Version that exhibits the issue: 2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):1.3
* Desktop OS/version used to run Mod Organizer: Windows 10 64bit

**Comment by Evolution0** [comment]
Have you confirmed that Skyrim.esm and Update.esm are selected in the Data tab?

**Comment by simpson409** [comment]
i'm not sure what you mean, since the data tab has no checkmarks at all, and never had.

**Comment by Evolution0** [comment]
Sorry about that brain fart, I meant the Plugins tab, then I realized that the main esm files are permanently enable anyway.

Too bad I don't have Skyrim currently installed to debug :/

Which version of DSR are you using? There was an old issue DSR had and I'm not sure exactly which version fixed it but this is basically the error that would come up.

**Comment by WizardShotTheFood** [comment]
I'm having the same thing occur with ASIS (version 1.42.5.H). Works fine in Mod Organizer 1.3.11. broken in 2.1.0.1.

**Comment by erasmux** [comment]
Should be fixed with the latest 27/12 dev build on the discord channel. Please test.

**Comment by Silarn** [comment]
Please verify the fix or I will close the issue within the next week or so.

**Comment by WizardShotTheFood** [comment]
It appears to work now. Sorry for the delay, holiday aftermath is kind of a thing for me.

**Comment by Silarn** [comment]
Thanks!
