### ISSUE TITLE
Qt: Untested Windows version 10.0 detected! (Mod Organizer 1.3.11) 

### ISSUE THREAD

**Issue by Arminton** [LePresidente/modorganizer#159]
# The problem

I try to download mods for the "Classic" Skyrim and I can't do it from Mod Organizer. Simply MO doesn't react to the download button, although nxmhandler.exe says it is properly directed.

# Environment

* Mod Organizer Version: 1.3.11 (for Classsic Skyrim)
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro, version 1709

# Details

Executing the helper.exe archive shows the following message

    Qt: Untested Windows version 10.0 detected!
    Invalid number of parameters
    -1

# Link to Mod Organizer logs

## USVFS
*I must apologize, but I am pretty new reporting issues, and I am not sure what this is about, and how to report it properly. If somebody may explain what is this log, and the interesting part of it, I'll upload it as fast as I can. Sorry for the inconveniences.* 

## MO Interface
*Looking the mo_interface.log there anything related to the issue mentioned, as the MO don't react to the download button. If you want, I upload it nevertheless*

**Comment by Evolution0** [comment]
This is the Mod Organizer 2 repo so.. have you tested with one of the latest builds in the Discord?

I've used 1.3.11 for Fallout: NV under Windows 10 Pro myself without issue, from looking up the that error message it seems harmless so I would check that you actually have nxm links associated correctly, for me that meant doing so via `Settings > Nexus > Associate` as using the option when installing did not work.

**Comment by Arminton** [comment]
Yikes... Sorry for the missplacing. I saw [that](https://github.com/TanninOne/modorganizer/issues/1144), and I was directed to this site from the MO from Classic Skyrim... My bad, sorry.

Regarding of the proposed check, I already done it, without any positive result. I understand though this is not the place for my question, so I thank you for your time, but I will understand if the post is closed

**Comment by Evolution0** [comment]
If its still a reproducible issue on the latest version its something that would need to be fixed regardless so I'm sure the maintainers will keep the issue open till its either been fixed or proven that it no longer effects the newer releases.

What browser are you using? And when you first attempted to click a download link did it ask if you wanted nxmhandler to open those types of links? If you said no it simply fails to work after that until you manually go in and fix it.

**Comment by Arminton** [comment]
It didn't ask anything, and I use Firefox. But, problem solved. I looked if maybe the problem is in the browser and seems that for an unkown reason the configuration was messed up on it, ignoring MO. Touched the nxm plugin and everything solved (strange, because a few days before it was working...).

Thanks for the support.
