### ISSUE TITLE
Save Game Wierdness

### ISSUE THREAD

**Issue by glade8r64** [LePresidente/modorganizer#16]
Save games are not being read by interface for missing esps.  Could be a Skyrim SSE issue?  Will be checking the Bethsoft forums for possible related errors.  Save game panel shows "missing esps: not working due to savegame weirdness".  I will attach a recent savegame and my current load order from loadorder.txt.

[lockedorder.txt](https://github.com/LePresidente/modorganizer/files/678190/lockedorder.txt)

**Comment by ZachHaber** [comment]
I wrote that line to try and make it so people wouldn't make a post about that on here.
The problem is that Bethesda used lz4 compression on the save files, which makes sense. The problem is that the compression starts before the esp list.
At the next release, it should be working fine.

**Comment by glade8r64** [comment]
Thanks for the response. I'll look forward to seeing the next release1
