### ISSUE TITLE
Left Panel Mod Priority reorders when mod is renamed

### ISSUE THREAD

**Issue by CptMcSplody** [LePresidente/modorganizer#164]
# The problem

The priority of the mods in Left Panel are reordered when  a mod is renamed using a number or special character at the start of the Name. Reverting mod rename straight away fixes priority order.

# Environment

* Mod Organizer Version that exhibits the issue:
  v2.1.0.1
  Lepresidente - 26/12/2017
  Latest Dev build of MO2 2.1 branch (2017-12-26)

* Last Mod Organizer Version that did not exhibit the issue (if applicable):
   Silarn - 15/12/2017
Full Build:
https://www.dropbox.com/s/boo0l2ed8ta8qw7/Silarn_15.12.2017_archive_test.7z?dl=0

* Desktop OS/version used to run Mod Organizer:
   windows 10 latest release update
# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs
debug
[1226/113227.930:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
[1226/113404.575:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 

## USVFS
https://pastebin.com/19Q4dmzt
https://pastebin.com/hh11Ha3j

## MO Interface
https://pastebin.com/q8e0KQv5

**Comment by erasmux** [comment]
Should be fixed in the 26/12 dev build. Please test.

**Comment by CptMcSplody** [comment]
its fixed
