### ISSUE TITLE
Local Game Settings and Savegames are not working

### ISSUE THREAD

**Issue by foxness** [LePresidente/modorganizer#17]
I have a profile with **Local Game Settings** and **Savegames** _checked_ but when I run the game it uses game settings and savegames from **Documents\My Games\Skyrim Special Edition**.

**Comment by fireundubh** [comment]
I can confirm that this issue also exists on 2.0.8.2 with Fallout 4.

**Comment by Freso** [comment]
Probably either this or #14 should be closed as a duplicate.
