### ISSUE TITLE
MO2 CTD when BSA are extarcted.

### ISSUE THREAD

**Issue by Darkladylexy** [LePresidente/modorganizer#172]
# CTD when loading a save or starting a new game when BSA's are extracted

CTD when loading a save or starting a new game when BSA's are extracted this can be easily tested by installing Legacy of the dragonborn along with it's 2K High resolution texture pack.

https://www.nexusmods.com/skyrimspecialedition/mods/11802

# Environment

Mod Organizer 2 v2.1.0.1

# Details

The 2K High Resolution Texture pack contain a dummy esp which mean if you extract you don't need the esp thus save an esp slot. The CTD does not occur if the BSA is left Unextracted

**Comment by CptMcSplody** [comment]
Just to rule out any issues with the texture pack
can you download nifscan https://www.nexusmods.com/skyrim/mods/75916/?tab=files.
copy the nifscan.exe to the root folder that contains the texture folder for the 2K High Resolution Texture.
like so https://i.imgur.com/GX8chkk.png
 
Open powershell using shift right click.
https://i.imgur.com/mfdF1Bc.png

copy & paste this and run
 .\nifscan.exe | Select-String -Pattern 'SSE' -CaseSensitive -Context 4,2

**Comment by Darkladylexy** [comment]
I have Windows 7 so as far as i know i don't have powershell

**Comment by CptMcSplody** [comment]
Was this on loose textures?
can you hide any files listed as being unreadable & try again.

**Comment by Darkladylexy** [comment]
yes this was on loose files and it looks to be pretty much it cannot read any files from that mod. I am trying on the lower resolution i will report back on that test.

**Comment by CptMcSplody** [comment]
What are you using to extract the files? B.A.E or BSA browser?

**Comment by Darkladylexy** [comment]
I just set MO2 BSA Extractor to True and let MO2 extract the files

**Comment by CptMcSplody** [comment]
Yeah don't use that, it doesn't work. Grab this https://www.nexusmods.com/fallout4/mods/78/ this and use it instead.

**Comment by CptMcSplody** [comment]
If that works for you can you mark this closed.

**Comment by Darkladylexy** [comment]
Ah my back I didn't realize the BSA Extractor from MO2 didn't work to confirm I was able to extract the mod no issues.
