### ISSUE TITLE
FO4Edit run through Modorg2 Loads DLCS on Bottom

### ISSUE THREAD

**Issue by rylasasin** [LePresidente/modorganizer#174]
# The problem

When FO4Edit starts, it loads the DLCs through the bottom, AFTER all the rest of the ESMs.

# Environment

* Mod Organizer Version that exhibits the issue: **2.1.0.1**
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): **Beta 4.3**
* Desktop OS/version used to run Mod Organizer: Windows 7.

**Comment by CptMcSplody** [comment]
and if you run a sort, what happens?

**Comment by rylasasin** [comment]
Nevermind I figured it out. I just needed to update FO4Edit to 3.2
