### ISSUE TITLE
2.0.8.1b: Extraction fails with some large archives

### ISSUE THREAD

**Issue by fireundubh** [LePresidente/modorganizer#18]
Extraction fails with at least two Skyrim SE mods of which I'm aware:

* Vivid Weathers SE
* RealisticWaterTwo with Watercolor optional

The extraction dialog will freeze toward the end of the process, and MO will become nonresponsive.

There is also an issue with SMIM. Extraction will succeed, but the dialog will flash repeatedly at the end.

**Comment by bartmoss** [comment]
Can confirm MO freezes at 99% for Vivid weathers. In my tests, it happened when I had selected the "extended rain sounds" option; the other options do not seem to be a problem.

**Comment by bartmoss** [comment]
Can confirm MO freezes at 94% for RW2. This only seems to happen when "extended ambiance" or "watercolor" options are selected.

I should also note that it isn't during extraction, but during the installation phase for both VW and RW2.

**Comment by LePresidente** [comment]
Yea my tests show it freezing as soon as it tries to copy the wav files to the mod folder. Haven't been able to find out why yet though

**Comment by adrianleong98** [comment]
Verified that this problem still persists with the 2.0.8.2 build. Installing the Qaxe's Questorium mod also causes this issue, but uncertain if it is the exact same problem.

**Comment by LePresidente** [comment]
Ok tracked down this issue, The 16.04 7zip api changes broke things going to revert back to 9.20 for now  till we can fix modorganizer-archive.

**Comment by LePresidente** [comment]
Tested installing both on 2.1.0, Cant reproduce.

**Comment by Silarn** [comment]
Either using 9.x or my workaround for newer versions fixes this issue.
