### ISSUE TITLE
MO 2 Tutorial Stuck on Download (originally "Help UI not working")

### ISSUE THREAD

**Issue by EverydayWarrior** [LePresidente/modorganizer#181]
I installed MO2 today, and when it started I opted for the tutorial.  It became stuck not too far in, though, when it reached the point where it said to download and install a mod to continue.  I downloaded, but it wouldn't register in the Downloads window though the log at the bottom said I had requested the download.  Anytways, I never mind looking through help files when I need help, but after having to restart MO2 to get out of the tutorial, the "Help UI" choice in the menu does nothing.  I click on it.... nada.

I'm experiencing several other problems, but if I could access the Help files maybe I could find my answers there.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10

# Link to Mod Organizer logs
## USVFS

https://gist.github.com/EverydayWarrior/46bb2bf4fdbd42ffac89ec0cbb81b66e

## MO Interface

Included in the above gist

**Comment by CptMcSplody** [comment]
@EverydayWarrior Yeah tested it there, a bit confusing, but you have to install the mod as well. 
These might need to be broken into seperate steps.

**Comment by EverydayWarrior** [comment]
It's difficult to screenshot nothing happening, so instead I screenshotted a replication of what began it all: the failed tutorial.  I'm most likely missing something, so please let me know!  I tend to be very logical, but sometimes my logic doesn't line up with things other people see as logical. xD

I numbered the screenshot for ease of explanation.

1. Note that the tutorial dialogue blocks a portion of the viewable window making it difficult to see a small portion of the download panel and a majority of the logs at the bottom.  I'd REALLY suggest making the dialogue moveable or somehow coding it to appear outside the main UI.  Due to this difficulty, I've provided...

2. ... a copy of the log report copied and pasted into Notepad.  You can see there the progression of the download that I attempted for the mod "Map Markers Complete".

3. The tutorial states that when a mod is downloaded, it shows up in the download panel.  Perhaps I'm missing a step.  I used the "Download with NMM" after checking various boxes and providing various pws, and the log would seem to indicate that it worked, but the download, as you can see, doesn't show up in the downloads panel.

4.  Just to be thorough, I also scrolled to where it would show up in the Mod list to the left to show that it's not there.

I'm having a host of other issues, but they may be either misunderstandings, or perhaps caused by my having to close out the program to escape the seemingly stuck tutorial.  If I'm missing something, may I suggest perhaps rewording the tutorial to make it a little clearer? :)

-- EverydayWarrior

![mo2 tutorial screenshot](https://user-images.githubusercontent.com/34949069/34456922-b3195280-ed70-11e7-8f87-02b3135cca5c.png)

**Comment by EverydayWarrior** [comment]
Btw, I worked customer service for a .com for a while and I know how thankless a job like that can be.  Thank you for your time and effort to provide support and fixes to your product!  My husband is also a developer (mostly back end stuff) so I see at times the frustration of something not quite working the way it was intended when everything seems to be in order.  He always manages to figure it out in the end as I'm sure you all will with any bugs the system has currently.  Many thanks!

(As you can probably see, I'm more of an academic than a tech person, so it's entirely possible that I'm just looking at MO2 differently than many users and thus not understanding it completely.  Thank you for your patience!)

**Comment by CptMcSplody** [comment]
@EverydayWarrior Ah right, well you can't see the downloads tab at the moment.
https://i.imgur.com/WTov92m.png

Press the arrow to the right of saves.
You should be able to see it then.

**Comment by EverydayWarrior** [comment]
XD  THANK YOU!!!  As an ex-customer servicer, I suggest mentioning the arrow in the tutorial. XD

Now I can move on to figure out why the heck the checkboxes don't seem to activate or deactivate the mods and why I don't have the option to remove them that some others seem to have...
