### ISSUE TITLE
Autosaves

### ISSUE THREAD

**Issue by BuddyKidd** [LePresidente/modorganizer#186]
# The problem

MO2 is saving every autosave rather than just two or three.   I am using the latest build and using local saves. 

# Environment

I am using the latest build from NEXUS, Windows 10.

**Comment by Silarn** [comment]
Autosave files should be handled by the game itself. We probably need a screenshot or log to know what the problem is.

(And I know my local autosaves are working normally.) I can only guess that the game is having a problem deleting the old autosaves for some reason.

**Comment by BuddyKidd** [comment]
What logs do you want?

**Comment by Silarn** [comment]
I'd prefer a screenshot of the save files first just to see if that tells me anything.

**Comment by BuddyKidd** [comment]
I have been testing to see if I can find the cause.  I found that I had SKSE installed improperly.  When I fixed that I no longer had the autosave numbers going up past three.  However, there is still a problem in that the old autosave numbers one through three are not being purged.  This is happening using local saves and also if I switch over to the saves in the documents folder.  Here is a screenshot of the local saves. 

https://mega.nz/#!5vYDzI4Y!OZ7Uz8IRolJknya3N4yt7jL7Y2JwpmZvFB6I-BZtHGA

**Comment by Silarn** [comment]
So if you delete the old skse files they're not being deleted with new saves? I'm not sure this is something MO related.

**Comment by BuddyKidd** [comment]
I am not sure either but it only started happening recently.

**Comment by Silarn** [comment]
Can you confirm it continues if you delete the old skse files?

**Comment by Silarn** [comment]
Since this is a known SKSE64 bug, I'm closing this ticket.
