### ISSUE TITLE
Skyrim doesn't seem to shut down if launched through MO

### ISSUE THREAD

**Issue by bartmoss** [LePresidente/modorganizer#19]
Using Mod.Organizer-2.0.8.1.exe (Beta 4.1), it seems that Skyrim doesn't shut down properly after I quit the game. I get back to desktop, but skyrimSE.exe stays in the processlist and I have to kill it eventually.

**Comment by bartmoss** [comment]
This also happens when starting it via the launcher; when clicking "exit", the launcher just freezes in place.

**Comment by Silarn** [comment]
I don't believe this is currently an issue. I'll reopen if you can replicate on our latest builds.
