### ISSUE TITLE
MO 2.08.1 update - CreateProcessW remove quotes from command line

### ISSUE THREAD

**Issue by sheson** [LePresidente/modorganizer#2]
If an executable started through MO it uses the CreateProcessW function, but quotes used in the command line parameters are removed causing the process to receive wrong command line parameters.

To reproduce, start C:\Windows\System32\cmd.exe through MO and execute a command like

more "C:\SteamLibrary\SteamApps\common\Skyrim\Papyrus Compiler\ScriptCompile.bat"

Current result 'Cannot access file' error message, because the quotes are removed the path is cut off at the space between 'Papyrus' and 'Compiler'

**Comment by ZachHaber** [comment]
Until we are able to figure out the cause of this, I believe you can escape out the quotation marks which will cause them to appear properly. To do that, use \" instead of " while in the command prompt.
You could also run it using the cmd.exe as the binary and
/k "C:\SteamLibrary\SteamApps\common\Skyrim\Papyrus Compiler\ScriptCompile.bat"
as the argument in MO2.
I am currently completely unsure as to why this is occurring.

**Comment by sheson** [comment]
Escaping the doublequotes with an blackslash + doublequote (1 backslash followed by 2 doublequotes) works, however using that trick breaks the example command line in MO 1.x so unfortunately that is a general workaround.

Note that the example is not trying to starting a batch with cmd exe, but creates another child process from within the cmd prompt spawned by MO to show the content of the bat file. This is probably happening in usvfs.cpp or hooks/kernel32.cpp

Normal
`more "e:\SteamLibrary\SteamApps\common\Skyrim\Papyrus Compiler\ScriptCompile.bat"`
Log Error:
 `18:56:20.653 <6944:6232> [D] CreateProcessW [applicationReroute.fileName()=C:\Windows\system32\more.com] [cmdline="more" e:\SteamLibrary\SteamApps\common\Skyrim\Papyrus Compiler\ScriptCompile.bat] [blacklisted=0] [res=1]`

Escaped
`more \""e:\SteamLibrary\SteamApps\common\Skyrim\Papyrus Compiler\ScriptCompile.bat\""`
Log Success:
`18:54:12.711 <6944:6232> [D] CreateProcessW [applicationReroute.fileName()=C:\Windows\system32\more.com] [cmdline="more" "e:\SteamLibrary\SteamApps\common\Skyrim\Papyrus Compiler\ScriptCompile.bat"] [blacklisted=0] [res=1]`
