### ISSUE TITLE
Issue Installing CCO

### ISSUE THREAD

**Issue by cchivers1516** [LePresidente/modorganizer#200]
# The problem

I'm currently attempting to install Character Creation Overhaul to Skyrim Special Edition, but I keep running into an error that does not allow me to do so. I can download the mod just fine, I simply am unable to install it.

# Environment

* Skyrim Special Edition Mod Organizer v.2.1.1
* N/A, unsure
* Windows 10 Pro 64-bit

# Details

This is the error message I see when I try to install the mod:
Could not load file or assembly 'file:///C:\Users\(Username)\Desktop\All of the Everything\Games\Skyrim Folder\Mod Organizer\NCC\GameModes\SkyrimSE.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

After clicking OK, I see this message:
installation failed (errorcode 5)

There is a box behind those boxes that has a progress bar and a message that reads: 
Running external installer. Based on Nexus Mod Manager by Black Tree Gaming Ltd.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Silarn** [comment]
Okay, so do you have that dll in your mod organizer path?

**Comment by Silarn** [comment]
Okay, so do you have that dll in your mod organizer path?

**Comment by cchivers1516** [comment]
...When you say path, do you mean if I have that specific dll in my GameModes folder in NCC, etc?

**Comment by Silarn** [comment]
Do you have anything under MO2\install\bin\NCC\GameModes\data?

**Comment by Silarn** [comment]
Based on a google search, this may also be due to the files being blocked. View the DLL properties and see if it's got an 'Unblock' button.

**Comment by cchivers1516** [comment]
Under GameModes\data, I have both BOSS and LOOT 32 and 64 dlls. For the second question, under which DLL should I look for this 'Unblock' button, and in what tab of the properties?

**Comment by cchivers1516** [comment]
New error message. I just tried unblocking every DLL that caused problems, and now I'm getting a new error message that reads:
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See (url) for more information.

What do I do now?

**Comment by Silarn** [comment]
It sounds like you still have files being unblocked. I assume you extracted from the archive release rather than using the installer. So you can either try unblocking the zip before you extract or open powershell and run this:
`Get-ChildItem -Path 'C:\Users(Username)\Desktop\All of the Everything\Games\Skyrim Folder\Mod Organizer\' -Recurse | Unblock-File`

**Comment by cchivers1516** [comment]
THANK YOU! That did it!
