### ISSUE TITLE
Possibly broken interaction between MO2 and SSEEdit

### ISSUE THREAD

**Issue by Ktithra** [LePresidente/modorganizer#206]
# The problem

All attempts at launching SSEEdit via MO2 (with or without any mods selected) results in either "Access Violation" or "Error 216," and this is the only executable on my system that gives that error, removing the suspicion of a trojan being on this machine (which is what all my Google-searches for Error 216 pointed toward.)

# Environment

SSEEdit 3.2.1
Mod Organizer 2.1.1
Skyrim Special Edition 1.5.23
Windows 7 Home Premium 64-bit SP1
16GB RAM
nVidia GTX970

# Details

I can launch SSEEdit directly, and it seems to attempt to load just fine, but (obviously) without my mod selection.

I have verified that my installation of MS Virtual C++ 2015 runtime is installed correctly by reinstalling it directly from the link provided in the sticky post on the MO2 Nexusmods page.

I recognize that this issue may not be strictly MO2 or SSEEdit, and I have posed this to the SSEEdit folks, but might this be some sort of strange interaction between SSEEdit and MO2? For the record, I have re-downloaded and re-installed both programs in my troubleshooting attempts.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/Ktithra/b3855b46d3ce8d2323cada0a0c03b8fd

## MO Interface
https://gist.github.com/Ktithra/344fb0331c6f12b9072f890bf020a44a

**Comment by 352** [comment]
I had this identical problem.  The upgrade to usvfs 0.3.1 Beta fixed it for me.

**Comment by Ktithra** [comment]
Hm.  Upgrading usvfs sounds like it might be a possible solution.  Did you find that at a separate location, or did you just pull source from here and compile it yourself?  What was your upgrade process?

**Comment by 352** [comment]
I got the upgraded usvfs files from the Discord channel in #builds.  
https://discordapp.com/channels/265929299490635777/379225566122999808

**Comment by Ktithra** [comment]
Aaaaaaaaaaand that's my SSEEdit issue sorted!  You have my thanks for the direction, @352 !

**Comment by Silarn** [comment]
Glad the usvfs updates fix this issue for you. We should be able to release soon with these updates.
