### ISSUE TITLE
URLs for visitng Mods on Nexus are wrong

### ISSUE THREAD

**Issue by bartmoss** [LePresidente/modorganizer#21]
When right-clicking on a mod and selecting "visit on Nexus", it seems MO uses URL of the format:

http://www.nexusmods.com/skyrimse/mods/xxxx/

While it should be:

http://www.nexusmods.com/skyrimspecialedition/mods/xxxx/

**Comment by seancojr** [comment]
I report having experienced this as well. My workaround has been to utilize [Tampermonkey](https://goo.gl/lF8xMX) (for Google Chrome) and this [script](https://greasyfork.org/en/scripts/24484-nexus-fix-skyrimse-links) (Nexus: Fix SkyrimSE links).

**Comment by LePresidente** [comment]
You sure you using the latest version, Cant reproduce.
