### ISSUE TITLE
Cannot call proxy library through ENB file in Skyrim SSE with MO2

### ISSUE THREAD

**Issue by Qwinn1** [LePresidente/modorganizer#212]
# The problem

I am attempting to get Helixmod 3D Vision fixes working with an ENB through MO2.  As both use a file called d3d11.dll, I need to use a proxy library.  It works fine with Nexus Mod Manager - all I need to do is set up a proxy library in the enblocal.ini as follows:

[PROXY]
EnableProxyLibrary=true
InitProxyFunctions=true
ProxyLibrary=d3d11.dll3d

...where that proxy library is the Helixmod fix.  

Both the ENB and 3D fixes work without a hitch when doing it this way in NMM.  In MO2, silent exit.  No logs or dumps are created anywhere, even with logging set to Debug.  It just dies, almost immediately.  This is with only a single mod installed (Obsidian Weathers) for testing.  I haven't even added SKSE64 yet.

I know probably none of you has 3D Vision, but... there must be other proxy libraries people use - SweetFX, maybe? - that need to be run via proxy libraries.  Is there maybe some setting I need to switch in modorganizer.ini to make this work?

MO2 is fantastic, so much better than NMM.  I was willing to sacrifice MO2, only because 3D+ENB is glorious, so as to not have to bother you guys, and I've been working my mod setup in NMM for almost a month.... and today, NMM crashed and when I loaded, my entire install was deactivated and basically destroyed my entire mod setup.  A month's work wasted.  I'll never risk using NMM again for anything beyond the simplest setup.  Please help!!  

I also asked at Helixmod if they had any advice.  I tried their own method of calling proxy libraries, wherein I had the 3D Fix as the d3d11.dll and my enb's dll as the proxy I was calling, but that did not work with MO2 either - and, it must be said, that method didn't work on my first try in NMM either, though I didn't pursue that avenue very far as I had the working alternative.

Here's hoping this is as simple as flipping a switch in modorganizer.ini.  I tried joining the Discord dev chat room but was unable to find the channel (typing anything in the search box pulls up nothing at all, actually) so posting it here seems to be my only hope.  Thank you HUGE for any help you can provide.

# Environment

* Mod Organizer Version that exhibits the issue:  v2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:  Windows 10 Pro 64 bit version 1709

As MO2 just dies silently and immediately, creating no logs or crashdumps at all when attempting to have my enb call the Helixmod 3D vision proxy library, I cannot attach anything here.

- Qwinn

**Comment by erasmux** [comment]
Since you are already interested (or at least willing) to join the discord server, please use the link on the top of the main github page ([here](https://github.com/LePresidente/modorganizer)). In addition to asking for help interactively (for example on the #testers channel), two things I suggest you try:
1. Update to the latest build under #builds (at the time of writing, the nexus 2.1.1 release is still the latest build but there is a beta update for usvfs which includes quite a lot of fixes).
2. If the latest dev build doesn't resolve the issue, please follow the detailed instructions in the #info_for_testers channel to reproduce the issue with a 100% clean MO installation.

Find me on the discord channel for further interactive help as I am not sure I fully understand the issue you are experiencing.

**Comment by Qwinn1** [comment]
Thanks for your quick response.  FINALLY got into Discord... apparently it doesn't play nicely with Internet Explorer.  Got it working via Pale Moon browser.

Installing the latest beta from #builds didn't help.  So, hope to see you there!

**Comment by erasmux** [comment]
The issue can be reproduced by:
1. Downloading the http://helixmod.blogspot.co.il/2016/11/the-elder-scrolls-v-skyrim-special.html
2. Extracting all the files to the SSE game folder and renaming the new d3d11.dll to d3d11.dll3d.
3. Edit the proxy section in the enblocal.ini per the lines stated in the original post.
4. Running the game without MO will give a weird message but will load the game. Runing the game with MO results in an immediate CTD (technically not a crash but skyrim is "gracefully" existing immediately).

**Comment by Qwinn1** [comment]
Thanks tons for looking into it, erasmux!

I also started a thread at the ENBSeries forums just now, hoping they can maybe think of something that wouldn't occur to us that could cause a conflict.  The thread is here, you could maybe use it to throw any questions their way if you come up with any that only they could answer:

http://enbdev.com/enbseries/forum/viewtopic.php?f=21&t=5777&sid=028c6bb3de3f3509dd4e066e6897ad10

Thanks again!

**Comment by Qwinn1** [comment]
Apologies if that was inappropriate.  You'd said that you were short on time, and I thought maybe if Boris or whoever over there already knew of a limitation/conflict in how the proxy libraries are called, I'd find out and share the info with you.  I didn't mean to ask anyone there to actually work on the problem, just checking if they knew anything off the top of their head that could mess with that functionality (like, it's using some other DLL resource that can't be shared with any other process, something like that.)  Was just trying to help out, and certainly didn't mean to cause any drama.  Sorry if I did.

**Comment by Qwinn1** [comment]
Aaaactually... you may want to review the 3D thread again... bo3b reviewed my posted logs of trying to have the 3D fix call the ENB as a proxy and came to a conclusion that may, or may not, have an impact on this issue too.

**Comment by Qwinn1** [comment]
Hullo!  Just wanted to say - please don't spend any time on this for the moment.  I've been pursuing this on my own with the other players involved, and it really may NOT be a bug in MO2.  I've been chatting with the main dev at Helixmod, and he did in fact find a bug in his code dealing with proxy calls that may be responsible for what happened.  He sent me a test for calling the ENB from the 3D fixes via proxy library that *was* able to successfully start through MO2... though there are still some other issues.   So... please don't spend any more of your valuable time on this until we can confirm that it wasn't that 3D bug that was causing MO2 to crash (I don't have a build in my hands with JUST that fix yet to confirm.)  I'll definitely let you know the results.  Thanks regardless for your willingness to help!

**Comment by Qwinn1** [comment]
Oh, and I feel compelled to add:  thanks again HUGE for continuing development on MO2 in the first place.  Seriously.  I wound up deciding to give up on the ENB for the time being and go back to working with MO2, and it really is sooooo insanely better than any other option.  Incredibly stable, and fantastic functionality.  Tremendous work, guys.  I extend as many kudos and respects as someone who has coded professionally for 20 years can.

Anyway, will let you know how it goes!

**Comment by Qwinn1** [comment]
I will now attempt to close this request!  A fix to the Helixmod 3D Fixes proxy code did in fact eliminate the issue I was having of MO2 crashing when doing proxy library calls.  It now works with the ENB calling the 3D Fixes as a proxy, AND with the 3D Fixes calling the ENB as a proxy.  All is working splendidly.  Thanks so much for your time and help!
