### ISSUE TITLE
Anti-viruses detect Mod Organizer 2 as Trojan

### ISSUE THREAD

**Issue by reck0** [LePresidente/modorganizer#213]
# The problem

Anti-virus detects Mod Organizer 2.1.0 and 2.1.1 installers as Trojans.  Wondering if this is a case of the development source being poisoned.  To be clear this is the installer, not the vfs, the installer, as well as the uninstaller, downloaded from [here](https://github.com/LePresidente/modorganizer/releases) on github.

# Environment

* Mod Organizer 2.1.0 and 2.1.1
* Last Mod Organizer Version that did not exhibit the issue (if applicable): Beta 4.3 ( 2.0.8.3 )
* Desktop OS/version used to run Mod Organizer: Windows 10 v1709 (build 16299.125)

# Details

Virus total reports: 
MO 2.1.0 - https://www.virustotal.com/#/file/0da5f561a9e38a69f64b4a0567a934a1bd9902b294e83b01230f853daf3f8ade/detection

MO 2.1.1 - https://www.virustotal.com/#/file/9fdb7a459e53b8156d07f058db3bf3393cd5148deb7bd21851207160abb17f9b/detection

https://drive.google.com/file/d/1HjiIxajOXpiwXH7uxIjCRfoaMVXOumgi/view?usp=sharing

**Comment by Al12rs** [comment]
I have checked the type of virus that are being detected they say it could be a possible malicious downloader, but that is just what the installer needs to do: it download and install MO2 and its dependencies. No one touched the installer apart from @LePresidente as far as i know, and you can be pretty sure he is not trying to infect your PC. Those segnalations are just to inform you that that program can download and install other programs which could in turn potentially be dangerous.

**Comment by Sir1Twist** [comment]
I have never had a problem with MO, or MO2 and my anti-virus. Of course I run Avast, so that might be something. I know that the reports are false. If they were real, my Avast would stop the process, cold. What anti-virus are you running?

**Comment by Silarn** [comment]
This is a false positive and not really an issue with MO. Due to the nature of how MO works AVs will likely continue to flag false positives with USVFS and potentially the installer. (Plenty of installers download additional components though so not sure why this would set off an AV unless it's being extremely overprotective.)
