### ISSUE TITLE
MO2.1.1 will not open F4SE 0.6.5 after latest FO4 Update (1.10.64)

### ISSUE THREAD

**Issue by DisplacerBeast** [LePresidente/modorganizer#214]
I do not know if anyone else has experienced this, but I've run into a bit of a problem with the newest update for Fallout 4--specifically, the new F4SE 0.6.5 that was released in order to accommodate FO4 v1.10.64. Mod Organizer has been working for me ever since I switched from NMM, but I cannot for the life of me get the new F4SE to run through it. I can start the game by manually clicking F4SE, but that means that my Mod Organizer mods won't load with it. I can load the normal game through MO, but then everything that relies on F4SE is disabled. Running MO2 as Admin doesn't help.

What happens is I click on the "Run" button with my F4SE link chosen from the drop-down menu, and MO locks itself like it normally does. However, after around ten or fifteen seconds, it then unlocks as though the game was never asked to run in the first place. No error messages, no flags, just nothing. The last thing that the messages at the bottom say is that my lockedorder.txt has been saved. Any help would be appreciated!

Here is the log after opening mod organizer and trying to play F4SE. I don't know if it will help, but I'm hoping it does:

12:38:41 [D] data path: C:/Users/Alexander Burnley/AppData/Local/ModOrganizer/Fallout 4
12:38:42 [D] Working directory: C:\Program Files\ModOrganizer\stylesheets
12:38:42 [D] Loaded settings:
12:38:42 [D]   base_directory=D:/Fallout 4 Mod Organizer II
12:38:42 [D]   cache_directory=%BASE_DIR%/webcache
12:38:42 [D]   compact_downloads=false
12:38:42 [D]   crash_dumps_max=5
12:38:42 [D]   crash_dumps_type=1
12:38:42 [D]   display_foreign=true
12:38:42 [D]   download_directory=%BASE_DIR%/downloads
12:38:42 [D]   force_enable_core_files=true
12:38:42 [D]   hide_unchecked_plugins=false
12:38:42 [D]   language=en_US
12:38:42 [D]   load_mechanism=0
12:38:42 [D]   log_level=1
12:38:42 [D]   meta_downloads=false
12:38:42 [D]   mod_directory=%BASE_DIR%/mods
12:38:42 [D]   nexus_login=true
12:38:42 [D]   nmm_version=0.61.13
12:38:42 [D]   offline_mode=false
12:38:42 [D]   overwrite_directory=%BASE_DIR%/overwrite
12:38:42 [D]   profiles_directory=%BASE_DIR%/profiles
12:38:42 [D]   use_prereleases=false
12:38:42 [D]   use_proxy=false
12:38:42 [D] initializing core
12:38:42 [D] usvfs log messages are written to C:/Users/Alexander Burnley/AppData/Local/ModOrganizer/Fallout 4/logs/usvfs-2018-01-26_17-38-42.log
12:38:42 [D] Initializing VFS <mod_organizer_instance, 1, 1, C:/Users/Alexander Burnley/AppData/Local/ModOrganizer/Fallout 4/crashDumps>
12:38:42 [D] initialize plugins
12:38:42 [D] looking for plugins in C:\Program Files\ModOrganizer\plugins
12:38:42 [D] loaded plugin "bsa_extractor.dll"
12:38:42 [D] loaded plugin "check_fnis.dll"
12:38:42 [D] loaded plugin "diagnose_basic.dll"
12:38:42 [D] loaded plugin "game_fallout3.dll"
12:38:42 [D] loaded plugin "game_fallout4.dll"
12:38:42 [D] loaded plugin "game_falloutNV.dll"
12:38:42 [D] loaded plugin "game_oblivion.dll"
12:38:42 [D] loaded plugin "game_skyrim.dll"
12:38:42 [D] loaded plugin "game_skyrimse.dll"
12:38:42 [D] loaded plugin "inibakery.dll"
12:38:42 [D] loaded plugin "inieditor.dll"
12:38:42 [D] loaded plugin "installer_bain.dll"
12:38:42 [D] loaded plugin "installer_bundle.dll"
12:38:42 [D] loaded plugin "installer_fomod.dll"
12:38:42 [D] loaded plugin "installer_manual.dll"
12:38:42 [D] loaded plugin "installer_ncc.dll"
12:38:42 [D] loaded plugin "installer_quick.dll"
12:38:42 [D] loaded plugin "pyCfg.py"
12:38:42 [D] loaded plugin "plugin_python.dll"
12:38:42 [D] loaded plugin "preview_base.dll"
12:38:42 [D] managing game at D:\SteamLibrary\steamapps\common\Fallout 4
12:38:42 [D] setting up configured executables
12:38:42 [D] configured profile: Default
12:38:42 [D] validating login cookies
12:38:42 [D] initializing tutorials
12:38:42 [W] Installed Qt WebEngine locales directory not found at location C:/Program Files/ModOrganizer/translations\qtwebengine_locales. Trying application directory...
12:38:42 [W] Qt WebEngine locales directory not found at location C:/Program Files/ModOrganizer\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
12:38:43 [D] loaded language en_US
12:38:43 [D] interface Ethernet seems to be up (address: fe80::a9f5:1c67:540a:bf74%ethernet_32769)
12:38:44 [D] reading save games from C:/Users/Alexander Burnley/Documents/My Games/Fallout4/Saves
12:38:44 [D] displaying main window
12:38:44 [D] retrieving credentials
12:38:44 [D] D:\Fallout 4 Mod Organizer II\profiles\Default\modlist.txt saved
12:39:20 [D] D:\Fallout 4 Mod Organizer II\profiles\Default\initweaks.ini saved
12:39:20 [D] D:\Fallout 4 Mod Organizer II\profiles\Default\plugins.txt saved
12:39:20 [D] D:\Fallout 4 Mod Organizer II\profiles\Default\loadorder.txt saved
12:39:20 [D] D:\Fallout 4 Mod Organizer II\profiles\Default\lockedorder.txt saved
12:39:20 [D] Load Mechanism: Mod Organizer
12:39:20 [D] USVFS DLL Name: usvfs_x64.dll
12:39:21 [D] enable local saves: 0
12:39:21 [D] Updating VFS mappings...
12:39:21 [D] D:\Fallout 4 Mod Organizer II\profiles\Default\archives.txt saved
12:39:21 [D] VFS mappings updated <linked 261 dirs, 5 files>
12:39:21 [D] Spawning direct process < "D:/SteamLibrary/steamapps/common/Fallout 4/f4se_loader.exe" , "" , "D:/SteamLibrary/steamapps/common/Fallout 4" >
12:39:21 [D] Waiting for spawned process completion : f4se_loader.exe (11236)
12:39:22 [D] Waiting for usvfs process completion : Fallout4.exe (4944)
12:39:59 [D] Waiting for process completion successfull
12:39:59 [D] D:\Fallout 4 Mod Organizer II\profiles\Default\lockedorder.txt saved
 [D]

**Comment by Sir1Twist** [comment]
It is weird. I get an error message myself. Here's the error: failed to spawn "F4se_loader.exe" : failed to start process (Access is denied [5]). We might have the same problem.

**Comment by Al12rs** [comment]
This very much seems to be caused by one of your installed mod that needs to be updated for F4SE 0.6.5. This can be verified by creating a new portable installation of MO2 without any mods and only installing FOSE, if FOSE runs correctly through MO then it is not MO's faul. Make sure there is nothig installed in actual game data folder other than FOSE (especially FOSE plugins that my need to be updated).
If this issue does not recieve further comments in the next week, it will be closed on the assumption that it was not MO's fault. Please report if your tests indicate the contrary.

**Comment by twizz0r** [comment]
Had this exact problem with the latest FO4/F4SE updates, It's not an MO issue. Here's a solution that worked for me: https://forums.nexusmods.com/index.php?/topic/6141393-f4se-wont-launch-with-new-11040-update/?p=57374361

**Comment by EsOmEs** [comment]
latest fo4 build and F4SE work fine for me. Must be a plugin issue.
