### ISSUE TITLE
Installation Failed: Unable to use any mods that have built in Installers

### ISSUE THREAD

**Issue by awsomemobs2000** [LePresidente/modorganizer#220]
# The problem

Just today, I launched Mod Organizer 2 and at first it was having errors starting up. Eventually after a few re-launches it worked. I launched the game, it worked fine. However I tried to install a new mod, and it gives me the following error message:
**Could Not Load file or Assembly
'file:///C:Users\My User\Desktop\Skyrim Mods\Mod Organizer\NCC\Gamemodes\SkyrimSE.dll' or one of it's dependencies. Operation not supported. (Exception from HRESULT: 0x80131515)**
This was the first time this has happened to me, and now I'm unable to even reinstall my current mods to change settings. 
# Environment

* Mod Organizer Version that exhibits the issue: v2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): The Current version up until today
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details
After clicking ok on the error message, I get the message **Installation Failed (error code 5)** which after clicking ok on that small window, then it disappears and so does the window saying **Running external installer....**.
# Link to Mod Organizer logs

## USVFS
https://gist.github.com/awsomemobs2000/d090a380932e47373d1ab5f3195ca129
## MO Interface
https://gist.github.com/awsomemobs2000/4c6ac9e2199fbd991033af5d236a4d30

**Comment by awsomemobs2000** [comment]
Alright I have now completed the post with Gists of the Logs.

**Comment by GrantSP** [comment]
Your logs aren't visible. Have you made them public?

**Comment by awsomemobs2000** [comment]
I've made them public now. It should work.

**Comment by awsomemobs2000** [comment]
It is currently in that location. I have checked to  make sure of it.

**Comment by GrantSP** [comment]
What are the Fomod installer settings in your Settings dialogue?
Also are these the full output of those logs?

**Comment by awsomemobs2000** [comment]
Fomod Installer (external) is where it's supposed to be, however installer_fomod.dll has been blacklisted for whatever reason. I think that may be the problem.

**Comment by GrantSP** [comment]
Did your AV software quarantine it or something?

**Comment by awsomemobs2000** [comment]
Nope. Though I may have an idea of what happened. When I had the mod loader open at one point almost right before the issue started, my computer blue screened because of me having too many things going on at once. Yea my computer is very unstable. I had Steam, LoL launcher, Roblox, and the mod loader up at once. Only roblox was really doing anything though. I'm thinking that my computer crash messed up the mod loader, So I came here to see if anyone could help me fix it.

**Comment by awsomemobs2000** [comment]
Ok, So I went under AppDATA, copied all of my mod files, to put them under a backup file. Then I deleted the APPDATA/Local/Modloader. I then started Modloader again and now it works. So I guess the issue is resolved.

**Comment by Silarn** [comment]
This is often caused by leaving the files blocked when extracting the archive version of MO2. You should always unblock the archive before extracting it per the installation instructions.
