### ISSUE TITLE
4K scaling

### ISSUE THREAD

**Issue by despotak** [LePresidente/modorganizer#223]
# The problem

ModOrganizer does not honor the scaling factor set by the OS. That means that on a 4K monitor it looks unusable small.

4K maximized window screenshot
![window](https://i.imgur.com/MZxMul7.jpg)

# Environment

* Mod Organizer Version that exhibits the issue: v2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro (Version 1709, OS Build 16299.214)

# Details

QT does not support high-DPI scaling before Qt 5.6

According to Nicolas Holthaus at [stackoverflow](https://stackoverflow.com/a/36057995/4575405)

> Qt has recently released a blog post 2 years ago about this issue [here](http://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/).
>
> High DPI support is enabled from Qt 5.6 onward. On OS X platforms, there is native support for High-DPI. On X11/Windows/Android, there are two methods to enable high-DPI detection per the blog post:
>
> 1. Set an environment variable
> 2. Setting an attribute in the program source code
>
> Setting `QT_AUTO_SCREEN_SCALE_FACTOR=1` in your system environment variables will fix the scaling issue.
> Additionally, setting `QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);` in your application source code should also allow automatic high-DPI scaling.
> 
> NOTICE: To use the attribute method, you must set the attribute before you create your `QApplication` object, that is to say:
> 
> ```c++
> #include <QApplication>
> 
> int main(int argc, char *argv[])
> {
>     QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
> 
>     QApplication app(argc, argv);   
>     return app.exec();
> }
> ```

**Comment by FaySmash** [comment]
have you tried to set the DPI-scaling to system? I did and MO looks properly now. Btw, afaik it would require a whole GUI rework to fix this, so not very likeable a fix will come in the near future.
![grafik](https://user-images.githubusercontent.com/30392780/35932543-282905c6-0c38-11e8-9454-1293c3c5d5b3.png)

**Comment by despotak** [comment]
Thank you @FaySmash for the pointer. 

Yes, this is how I use MO2 right now (with the `System (Enhanced)` option though), but this create another problem. That setting is passed to all the executables that are called through MO2 (LOOT, xEdit, xSE, and the game itself), which for me is not usable at all, since it breaks the actual game for me. The only thing I can do, is to revert back to the default setting when I done with installing/enabling/editing my mods and ready to launch the game.

To be more exact about my setup, I have 2 4K monitors, and I need to run my games on 1920x1080 Borderless Fullscreen (for performance issues). My system wide scaling factor is 200%, so a 1920x1080 windows should fill my whole screen. With the `System (Enhanced)` option enabled, while the window fills the monitor correctly, only the top left quarter is displayed (which is exactly 1920x1080 pixels). When I'm back home, I'll try the simple `System` option, to see if it offers different results.

I never said it is going to be easy or quick to implement. And upgrading to a newer QT is never easy (I believe MO2 uses QT 5.5). But I would like to add this as a [Feature Request], so the developers to become aware. 4K monitors are becoming more and more common, so high-DPI should be supported natively at some point.

**Comment by FaySmash** [comment]
@despotak oh I see. I'm running a similar setup (thought only one UHD monitor and 1 FHD with downsampling up to UHD enabled). tbh, I'm only running MO2 for two days now, applied around 20 mods but haven't even started the game yet lol. but I know the problem you're describing from programs like OBS. 
sadly a GUI rewrite won't come anytime soon, but hopefully it'll be added to the list!

btw an OT question: why do you run your games in FHD? what performance issues (except terrible scaling for AO of the ENB)? and have you tried to leave the scaling on "System (Enhanced) but stretch the top quarter image to all corners by using AutoHotkey? or use different tools for forcing borderless window like ENB or SpecialK? alternatively you can change the setting to "System" as you wrote, it should be displayed correctly but only in FHD what would be an issue for me.

**Comment by Silarn** [comment]
The application is using Qt 5.10 and we've been keeping it up to date thus far. I'm slightly dubious but if it's as simple as adding `Qt::AA_EnableHighDpiScaling` then I doubt it would be that difficult to add.

**Comment by despotak** [comment]
@FaySmash Color me impressed. The `System` option actually worked. I gave up on this setting long ago, when `System (Enhanced)` always worked better on anything I throw at it, so I never try `System`. So, at least, we have a workaround.

As for why I need to run the game on FHD instead of UHD, my graphics card (GTX 970) is not beefy enough to run most of my games (Fallout 4 in this case) in UHD with acceptable framerate (30+) while in FHD I can reach 50+ in most cases. I crave for the day that I will be able to upgrade to a 4K able card (1080 Ti or higher/newer) for a reasonable price.

@Silarn Good to hear that MO2 uses the latest QT. I don't know if it's as simple as adding `Qt::AA_EnableHighDpiScaling` (and I highly doubt  is as well myself) , but it's worth a try. If you need a tester, I'll be happy to try it out for you.

**Comment by FaySmash** [comment]
@despotak nice, I'm glad it worked out for you! (for me, everytime "System" mode worked better lol) this won't be a fitting solution for me thought because I want to play skyrim in UHD (my 1080 can handle with around 40fps with ENB and it doesn't matter much because of gsync and I play with gamepad anyway).
I'd be glad to be able to try out early fixes too!

**Comment by Al12rs** [comment]
I have uploaded a version with DPI scaling support enabled on discord in the #Builds channel. I could only test it with NVidia's DSR though. I have still found that forcing System scaling gives better results, but at least it should be acceptable now without it. Could someone could test it with an actual 4k display or a 1440p one and report if there are issues?

**Comment by FaySmash** [comment]
@Al12rs works flawlessly on 2140p! thank you very much for this quick fix! :D

![grafik](https://user-images.githubusercontent.com/30392780/36103774-9987a69c-1010-11e8-90c7-feeada0943d8.png)

**Comment by despotak** [comment]
@Al12rs I can confirm that on a 4K monitor with 200% scaling, everything (except the on-mouse tooltips) seems to scale correctly. Thank you for the quick implementation as well.

![image](https://user-images.githubusercontent.com/8259004/36105056-5675b6d0-101c-11e8-9d89-c91cd45a0338.png)

**Comment by FaySmash** [comment]
@despotak strage, the tooltips scale correctly for me on 200% scale. do you maybe still have this option set?
https://user-images.githubusercontent.com/30392780/35932543-282905c6-0c38-11e8-9454-1293c3c5d5b3.png

**Comment by despotak** [comment]
@FaySmash No, I made sure that I had it disabled to test. But I changed the scaling factor while the MO2 was running to see if it scales correctly if I revert back to 100% (which it did). This seems to broke the tool-tips though. When I rerun MO2 from a clean state the tool-tips worked fine as well. A really small kink on an extreme case, so no reason to worry about it.

**Comment by Al12rs** [comment]
Perfect this will be included in the next nexus release then. Thanks for the feedback.
