### ISSUE TITLE
Some FOMODS not installing properly

### ISSUE THREAD

**Issue by Cullerane** [LePresidente/modorganizer#225]
Hi, 
When trying to install Immersive Sound Compendium the extracting bar is stopped at 99% and won't bulge at all. All other Fomods  install correctly.  I am stumped. Please help.

Mod Organizer 2 standalone
Windows 10

![mo trouble](https://user-images.githubusercontent.com/36380408/36077225-2c9f5032-0f68-11e8-84b0-0a2a5e70a0ab.jpg)

Thank you

See attached file.

**Comment by Al12rs** [comment]
I assume you downloaded the 2.1 SSE (Non BAIN) version? (post a link next time so it is easier to reproduce) I will try to recreating the issue on my end. It could be a corrupted version of the file on some of the nexus servers, with big files it is not too uncommon.

**Comment by Al12rs** [comment]
Hmm... I get that too for some reason but cancelling and proceding to install the mod does not give any further indication that something is wrong. Really not sure what is going on there.

**Comment by Cullerane** [comment]
Thanks that's what I did : I carried on the install. Now I have another problem ie no combat sheathing nor hitting at enemy sounds. 
Skyrim ran from steam => sound ok
Skyrim skse ran from shortcut  => sound perfect
SKSE ran from mod organizer 2 => no combat nor sheathing sounds

Tried everything to moving installed game back and forth from my d sata drive to ssd... Zipping original skyrim sounds bsa ... to no avail 

can you help with this issue ?
