### ISSUE TITLE
Loads SkyrimSE ESMs with Fallout4 ESPs

### ISSUE THREAD

**Issue by XIIIRoxas13** [LePresidente/modorganizer#226]
# The problem

I have just booted up Mod Organizer 2 v2.1.1.

yesterday (2/10) it worked fine, as did all the previous times I have used it, until today (2/11). 

The problem is that its loading SkyrimSE's ESM files along side with Fallout4's ESP files. Its also showing me SkyrimSE's saves, and calling the current instance "Skyrim Special Edition Mod Organizer 2.1.1" 

I can still load up Fallout4 with the launcher or F4SE but all of the mods have been registered as uninstalled

When I switch to SkyrimSE everything is normal

# Environment

The Mod Organizer version i'm using is 2.1.1
The last version of Mod Organizer that I used is 2.1.1
* I am running Windows10

# Link to Mod Organizer logs

## USVFS
I would post my USVFS but I don't know where they are or what it would look like

## MO Interface
I would post my MO interface logs but I don't know where they are or what it would look like

**Comment by Al12rs** [comment]
Could you share a screenshot of the problem?

**Comment by Silarn** [comment]
It sounds like your fo4 instance got configured with the wrong game paths. Try editing the modorganizer.ini in the fo4 instance.

**Comment by XIIIRoxas13** [comment]
I have done a temp fix that is working well. 

I run Skyrim Legendary through Mod Organizer, Fallout 4 through Mod Organizer 2, and Skyrim SE through Vortex.

**Comment by Al12rs** [comment]
I too would assume something went wrong when setting up the game path. Closing this since I don't see it going anywhere since the tester has switched manager already.
