### ISSUE TITLE
LOOT can not be launched via "sort" button

### ISSUE THREAD

**Issue by bartmoss** [LePresidente/modorganizer#23]
LOOT version: 10.2

Upon starting loot via the sort button, an error pops up: "lootcli.exe has stopped working".

Upon selecting "close program", a small popup appears that states "loot failed. Exit code was: 3221225477".

**Comment by ZachHaber** [comment]
The sort button is currently not working. The most recent release of MO2 should have the button hidden. While I have done the coding to make the sort button work correctly, I have been informed that LePresidente is planning on removing the button entirely.

**Comment by LePresidente** [comment]
Waiting on pull request from @ZachHaber then the sort button will be returned.
