### ISSUE TITLE
Create Files in Mod Instead of Overwrite not working as intended

### ISSUE THREAD

**Issue by bartman726** [LePresidente/modorganizer#242]
# The problem

MO2's Create Files in Mod Instead of Overwrite not working as intended. Files are still going to Overwrite. Mod used to demonstrate was FNIS.

![image](https://user-images.githubusercontent.com/8009682/36611811-8d307ba2-18cc-11e8-8075-636e7d76ed9c.png)

Files are added to the overwrite instead
![image](https://user-images.githubusercontent.com/8009682/36611874-c6870880-18cc-11e8-8443-e8e8471de227.png)

# Environment
* Mod Organizer Version that exhibits the issue: MO 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Unkown
* Desktop OS/version used to run Mod Organizer: Windows 10 Professional

# Details

# Link to Mod Organizer logs

## USVFS
[usvfs-2018-02-23_19-03-16.log](https://github.com/LePresidente/modorganizer/files/1752834/usvfs-2018-02-23_19-03-16.log)

## MO Interface
[mo_interface.log](https://github.com/LePresidente/modorganizer/files/1752837/mo_interface.log)

**Comment by SuperSandro2000** [comment]
will be fixed in the next release. Meanwhile grab usvfs-beta5 from #builds in discord.

**Comment by bartman726** [comment]
God you work fast :) thank you very much
