### ISSUE TITLE
[Request] SSE should have an option to handle Skyrim links as well. 

### ISSUE THREAD

**Issue by MaddBomber83** [LePresidente/modorganizer#25]
There are several authors who are now posting SSE files still in their Skyrim Mod.  
There are a lot of texture packs from Skyrim being used in SSE.  
Several authors are having users download and disable ESP of Skyrim Mods and then downloading a SSE ESP.

It would be very useful if MO SSE could handle the download/meta from both repositories; hidden behind an option defaulted to off.

Thank you for your consideration.

**Comment by LePresidente** [comment]
Think this will not work, due to the way mod organizer currently works. For now marking won't fix, To install old skyrim mods, download manually and then install with mod organizer.

**Comment by MaddBomber83** [comment]
I've done a slight workaround simply for the download manager and meta data information.  Did you know/remember that Skyrim was only 5GB before mods and DLC/Texture packs....

I set up two instances of MO.  One for Skyrim and one for SSE.  They share the same base directory and I have the categories hard linked to each other.  I only use Skyrim for the download / meta data (gets it the right categories).  Everything else is done in SSE.

I do have to register the download links when swapping between the two.

I guess Skyrim Version Tracking will become less and less needed as time goes on.
