### ISSUE TITLE
MO2 Executables are not runnings the Mods from MO2

### ISSUE THREAD

**Issue by Zebstrikal** [LePresidente/modorganizer#250]
When I run executables for Classic Skyrim from MO2 they do not pull the mods. For example, TES 5 Edit only uses mods found in the actual Skyrim data directory, not the mod organizer directory. I am not sure why this is as Skyrim steam folder and the mod organizer folder are on the same disk so it's not a cross-disk issue

* Version: 2.1.1
* Last Version: My old mod organizer version was 2.0.7 I believe before I nuked it to start fresh

USVFS Log
https://pastebin.com/D8ZHXEbm
MO Interface Log
https://pastebin.com/RizWXe8S

It really sucks because now I feel like I nuked my game for nothing and im hoping that this is just an ini error or something

**Comment by Al12rs** [comment]
Could you tell me your windows version? complete of build number (run winver to get it).
Could I also ask you to set your log level to debug, close mo, restart mo, reproduce the issue, close mo and reupload the usvfs log?

**Comment by Zebstrikal** [comment]
Windows 8.1, and I just reproduced it and the issue itself doesn't actually detect anything wrong so the usvfs log is empty, but I can provide pictures of what im saying

Load Order:
http://prntscr.com/im4oxn
TES 5 EDIT:
http://prntscr.com/im4p44

**Comment by SuperSandro2000** [comment]
usvfs.log has always some debugging stuff in it. Could you please upload them as AL asked because otherwise we have no real information to work with.

**Comment by Zebstrikal** [comment]
Fixed it by downgrading to MO 1.3.11. The log was blank, acting like im new to this smh.

**Comment by SuperSandro2000** [comment]
Please don't post issues about MO1 here as it is no longer supported.

**Comment by Al12rs** [comment]
He wasn't posting about MO1 he just said it does not reproduce on Mo1. If the log was blank it could have been cause by the use of Ccleaner or something similar to clean the windows event log (which apperently breaks usvfs). In that case a system restart would solve that particular issue.
