### ISSUE TITLE
CTD with FNIS

### ISSUE THREAD

**Issue by MaddBomber83** [LePresidente/modorganizer#26]
I'm getting a lot of crashes all over the place with MO2 SSE.
I've narrowed down the most frequent crash:
- Launching GenerateFNISforUsers

I've uploaded a [DMP file here](https://s3.amazonaws.com/modorganizer/MaddBomber_Launching_FNIS_ModOrganizer.exe.dmp).

I don't feel like much help with so little information.

System Information:
- Windows 10x64
- Everything Skyrim is installed in c:\Games; not in a system folder.
- I am pushing hard against mod limits.
- Mod Organizer 2.0.8.1 rev 1cf368c
- FNIS version 7.0.Beta

**Comment by LePresidente** [comment]
Little out my depth and I can't fix this. Need a c++ developer to fix this.

**Comment by MaddBomber83** [comment]
Thank you for letting me know.  I don't have those skills either.

**Comment by LePresidente** [comment]
Going to leave this open for now, since it is an issue

**Comment by GrantSP** [comment]
I don't exactly what setup you are running but in my testing of MO2 I am yet to experience a CTD.
I also can't see why FNIS would be especially prone to causing CTDs.

As part of the MO support team in STEP I have seen a lot of errors when MO/MO2 is run as admin and it is calling a tool that doesn't have elevated privileges, or vice versa.

**Comment by LePresidente** [comment]
Yea might update the forum post to point to https://github.com/LePresidente/modorganizer/issues/10 rather. The issue occurs if any third party app writes to the overwrite folder then you open another app that then tries to write to overwrite folder again.

FNIS is a good example if you run FNIS twice it has always crashed.
