### ISSUE TITLE
Cant select what game I want to manage

### ISSUE THREAD

**Issue by Jojoten** [LePresidente/modorganizer#267]
# The problem

Mod organizor just immediately starts and has Skyrim SE selected and I cant find a way to fix this.
I have the 2.1.1 version installed. (Edit by AL12)

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface (Edit by AL12 pls upload this always)
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Jojoten** [comment]
Mod organizor just immediately starts and has Skyrim SE selected and I cant find a way to fix this

**Comment by Al12rs** [comment]
Top left button lets you choose to create a new instance just be sure to use a name that is not the same of the old instance. I highly advise to use the Dev build 0.2 available on the MO2 discord server: https://discord.gg/cYwdcxj  since I changed all the instance system and dialogs to avoid these kind of situations.
(You can edit the original issue btw)

**Comment by Jojoten** [comment]
thx a lot! 
but now I have a nother problem.....
When i truy downloading a mod it dosent show up on modorganizer, im using chrome.

**Comment by Al12rs** [comment]
You mean when downloading with Mod Manager from Nexus?

**Comment by Jojoten** [comment]
Yes

**Comment by Jojoten** [comment]
Is there a way to fix that?

**Comment by Jojoten** [comment]
when I use the 2.0.7 version I can start the download but then it pasues and when I try to continue it just says error.

**Comment by Al12rs** [comment]
You need to run nxmhandler.exe in the MO2 install folder and register active your install. In the mo2 settings there is also an associate nexus link button
All this can be found in the pinned post on the MO2 nexus page, together with the known issues and other workarounds.

**Comment by Al12rs** [comment]
I will close this now, if you have other problems feel free to open a new issue or come by the MO2 Dev discord server. We can't help you much on how to use MO though, just solve bugs and hear suggestions.

**Comment by Jojoten** [comment]
ok thx I solvet it in Another way.

btw ur support was rly good and quick, :D
