### ISSUE TITLE
2.x Filetime listing for Downloads doesn't work

### ISSUE THREAD

**Issue by tryguy** [LePresidente/modorganizer#29]
I had to shift my install around a bit, and when I now look at the new Downloads, it's all presented from 0-z fashion. That's appropriate for sorting by Name, but it's not how Filetime should work. I click between them, and there's no difference. It's like Filetime sorting doesn't work at all.

I didn't try this when I had my old (original) install, so I'm not sure it worked then. But I need it now (since I wanted to reinstall the mods in the order I downloaded them again), but it doesn't work. I have to literally look at File Explorer to see the timestamps.

**Comment by Silarn** [comment]
I can't replicate this. For me, filetime is the default sort and seems to work. Does this still happen with a recent build?
