### ISSUE TITLE
2.0.8.1 Plug in list not being remembered when external tools are used 

### ISSUE THREAD

**Issue by tryguy** [LePresidente/modorganizer#30]
This has probably been said before, but I wanna say it again.

When using Wrye Bash or sometimes even with LOOT, the changes are sometimes (or in the case of Wrye, all the time) ignored.

I'm glad someone is working on this. And, it does generally work for modding. But this issue would be a good one to focus on, since I regularly switch between LOOT and Wyre when testing out new mods to play with. If I had a stable mod list, this wouldn't be such an issue, but right now I need to hand enable/disable things before playing. Lots and lots of things, as it turns out, since Wrye merges quite a few of them when I use it.

Well, good luck with this. Oh, and if it was in doubt, this is when using MO for Skyrim SE.

Oh, but I think it also reset my plugin list for Skyrim somehow. I'm not sure it was intentional, but when I started MO 1 back up (which I think I'll continue to use for Skyrim), my plugins were all disabled. That was not good.

Anyway, I heard that this update was focused on getting LOOT compatibility. And it works, most of the time. But it still doesn't quite remember when plugins are intentionally disabled. I use LOOT, it orders things, I come back to see the list ordered, but with plugins that shouldn't be enabled, enabled.

Oh, and I should mention that sometimes the mod order from LOOT doesn't stick. But, I'm used to MO2 crashing every five minutes when using external tools, so I'm not sure I really notice the times it messes up like this.

**Comment by MaddBomber83** [comment]
I use [Sync Plugins Batch](http://www.nexusmods.com/skyrimspecialedition/mods/2827/?) to 'fix' this when it pops up.  It will even carry over from LOOT to Wyre Bash.

**Comment by LePresidente** [comment]
Can you check if this is valid? should of been fixed in 2.0.8.2b

**Comment by tryguy** [comment]
Yeah, this seems to be good. I just tried it with wrye bash, and I didn't have to manually uncheck all the merged mods. So, as far as I can see, it's a good fix.
