### ISSUE TITLE
2.0.8.1 Crashing quite regularly on Win 10

### ISSUE THREAD

**Issue by tryguy** [LePresidente/modorganizer#31]
Yeah, I hinted in my last issue that I was experiencing crashes regularly. It's gotten to the point where I need to do something, exit out of MO2 and then restart, and do the next thing. This mostly involves external tools, but also applies to LOOT. I can't run it straight after I fiddle with installs and such. I need to quit and restart to avoid MO2 crashing outright.

**Comment by MaddBomber83** [comment]
I've found my most frequent is FNIS (issue #26). I've also found that the external tools crash less frequently if you make a desktop link from MO2 and run them from there.

**Comment by Silarn** [comment]
32-bit/64-bit application swap bug - fixed in recent builds
