### ISSUE TITLE
2.0.8.1 Actitivity?

### ISSUE THREAD

**Issue by tryguy** [LePresidente/modorganizer#32]
I can't see any commits and things on here. Are you sure this is the main hub of development for MO2? Where exactly did 2.0.8.1 come from? Someone's HD?

**Comment by LePresidente** [comment]
I'm doing it when i have time, though updating the code to work with msvc 2015 and qt 5.7 is my main priority, And supporting any other devs to get this building and contribute.

**Comment by tryguy** [comment]
Fair enough. I was just curious about development.

If I encounter any other bugs, I'll make some more posts, but those that I've listed are pretty much what I've experienced so far. There might be other file types MO2 falls over with, but right now I only know of .wav files. Anyway, thanks for your offer to further MO.

**Comment by LePresidente** [comment]
Since this was a question. Closing.
