### ISSUE TITLE
Running FNIS (tool) from default install folder has problems

### ISSUE THREAD

**Issue by tryguy** [LePresidente/modorganizer#34]
I should probably warn people that running FNIS from that folder in AppData that MO2 seems to want people to use results in FNIS not being able to derive what version of Skyrim you've got.

So, better to move the SkyrimSE structure that's in AppData to someplace normal (like c:\UTILS for instance). I just did this and I now have no problems with FNIS animations. Before, I really couldn't get things to work at all.

So, this is just for people that get stuck.

**Comment by tryguy** [comment]
Anyway, there's an extra little thing going on. When I use FNIS to generate files, they go into the overwrite like they should.

But when I try to drag those out and put them in a folder I created with them the first time, it says all of them are ignored and won't overwrite them. This is different to how MO1 handles this. As it is, I'll probably leave them in the overwrite, or I may physically copy them over to the folder I want them in. Why is the silly program not following orders? I don't care what it thinks is right. It's wrong.

**Comment by MaddBomber83** [comment]
I've done the remove 'FNIS Patch' and then recreate it from the overwrite.
With the Batched Patch the sync to mod option works.  Does not work for FNIS for some reason.

**Comment by LePresidente** [comment]
Duplicate Bug of https://github.com/LePresidente/modorganizer/issues/7
