### ISSUE TITLE
Built-in .ini files not working

### ISSUE THREAD

**Issue by krisser143** [LePresidente/modorganizer#38]
The fallout4.ini and fallout4prefs.ini that ModOrganizer has per profile doesn't do anything at all. Whenever I change a setting in-game, it only writes to the .ini files in my 'My Games' folder, and not the profile .ini files. And when I make an edit to the .ini files which ModOrganizer has, it doesn't do anything at all.

**Comment by macronomicus** [comment]
This is the same for Skyrim Special Edition.  The two ini files are overruled by the My Documents versions,  I could have sworn the ini change was working for a while lol >.<  maybe I was just being too derp to notice. 

I am running MO with admin credentials, so I dont see how its loosing the battle for its profile folder as source of the inis.   Perhaps its something to do with folder permissions back from the game to MO when running as admin?

Loot, sseedit and all the other essentials are working just as good as old MO for me, so cheers for fixing up mo2!  I'm fine with the ini issue really, still better than NMM.

I cant confirm the saves bit from OP, Im not using local saves, basically seems like the same issue though.
