### ISSUE TITLE
Using desktop shortcut freezes game on exit

### ISSUE THREAD

**Issue by krisser143** [LePresidente/modorganizer#39]
If I use the desktop shortcut provided by Mod Organizer to load Fallout 4 it runs fine, and all mods get loaded. BUT when I 'exit and save' it just freezes. It might be related to the virtual file system being bugged when not launched directly from the application, thus crashing the game when it saves.
If launched from the Mod Organizer application however, then 'exit and save' works fantastic.

There has been problems with the virtual file system when using the desktop shortcut before

**Comment by Silarn** [comment]
I may have seen this issue launching F4 normally, so I don't know if this actually has to do with shortcuts. But this could still be a valid issue.

**Comment by Silarn** [comment]
Shortcuts have been refactored to essentially launch as if you ran the application inside of MO. There have also been improvements to how USVFS is handled when using external shortcuts that should resolve most hooking issues. I'm going to tentatively close this ticket as there hasn't been a response and these changes probably solved the problem.
