### ISSUE TITLE
Mod.Organizer-2.0.8.1 setup menu issue.

### ISSUE THREAD

**Issue by Stigma311** [LePresidente/modorganizer#40]
Greetings 
I have a problem! well small one. 

I try to get  Mod Organizer 2.0.8.1 do setup progress about 42% in the installing/downloading the whole setup was aborted for some reason. I think has to do with a file call  Qt5.5.7z  

I have install logs i can give you 

[install logs.txt](https://github.com/LePresidente/modorganizer/files/691868/install.logs.txt)

**Comment by MaddBomber83** [comment]
Have you tried a few times, without your virus scanner and nobody on the network.

I've seen this type of thing for a few files I have downloaded.  It was fine first, but then really slow.  Slow enough that the network didn't even know it was a download anymore.

**Comment by Stigma311** [comment]
well Last night I try both aways about 8 times. Download rate start out strong and got weak and just forgot was downloading like you said. 

good bit of news I got to to work on the 9th try . had to used USB tethering my phone connection but connection was very week. was only able to get 12 to 16 Kbs

**Comment by LePresidente** [comment]
well i'm migrating the installer to Wix and using a different file hoster for the external files, github is just bad when it comes to file downloads
