### ISSUE TITLE
2.0.8.2: Integrated archiver cannot handle some archives

### ISSUE THREAD

**Issue by fireundubh** [LePresidente/modorganizer#48]
Some archives cannot be handled by the integrated archiver despite sharing the same extension as archives that are successfully opened. 7-Zip can open these problem archives just fine.

**Tested Mod:**
http://www.nexusmods.com/newvegas/mods/35979

**More Perks:**
This archive was not opened:
```
06:18:54 [D] nexus category id 71 not mapped
06:18:54 [D] mod id guessed: More Perks 2_4_6-35979-2-4-6.7z -> -1
06:18:54 [D] passed mod id: 35979, guessed id: -1
06:18:54 [D] using mod name "More Perks" (id 35979) -> More Perks 2_4_6-35979-2-4-6.7z
06:18:54 [D] Failed to open  "E:/ModOrganizer/Games/FalloutNV/downloads/More Perks 2_4_6-35979-2-4-6.7z"  using  "7z"  (from extension)
06:18:54 [D] integrated archiver can't open E:/ModOrganizer/Games/FalloutNV/downloads/More Perks 2_4_6-35979-2-4-6.7z: unsupported archive type (6)
```

**More Perks for Companions:**
This archive belonging to the same mod was handled correctly:
```
06:20:25 [D] nexus category id 71 not mapped
06:20:25 [D] mod id guessed: More Perks for Companions 1_0_6-35979.7z -> -1
06:20:25 [D] passed mod id: 35979, guessed id: -1
06:20:25 [D] using mod name "More Perks" (id 35979) -> More Perks for Companions 1_0_6-35979.7z
06:20:25 [D] Sound on the top level
06:20:25 [D] Sound on the top level
```

**Properties:**
Here are the properties of the two files according to 7-Zip:

![2017-01-17 06_25_50](https://cloud.githubusercontent.com/assets/1261664/22024180/f41de5de-dc7d-11e6-9e80-7a204c10e901.png)

![2017-01-17 06_26_26](https://cloud.githubusercontent.com/assets/1261664/22024179/f416ee00-dc7d-11e6-8d10-358a04ca7baa.png)

7-Zip tests produced no error results.

**Comment by ZachHaber** [comment]
The reason the first one failed to open is because the first file was misnamed. It should be a .zip file rather than a .7z.

**Comment by LePresidente** [comment]
Since this was compressed with pkzip it has a file header of "PK\x3\x4\x14" that 7zip doesn't even list when we query 7zip for the file signatures of known compression types. 

Currently MO2 will use the extension then try check if the signature is in the 7zip known list. If neither work will show the error. none of the zip signatures are currently working since modorganizer-archiver doesn't call kMultiSignatures yet during "ArchiveImpl::loadFormats()" in archive.cpp

**Comment by LePresidente** [comment]
Temporary fix we have done is roll back the 7zip api to 9.20, Modorganizer-archive needs a bigger revamp to work with the new api correctly then was originally thought.

**Comment by Silarn** [comment]
While the workaround to prevent crashes on the latest 7z libraries is... not great, it does seem to work. Since that's only tangentially related to this ticket, I think we can close this?
