### ISSUE TITLE
2.0.8.2 - failure and/or crash on game exit

### ISSUE THREAD

**Issue by noctred** [LePresidente/modorganizer#53]
Without fail, every time I quit FO4 with a simple exit to desktop via menus, Mod Organizer dies.

Initial symptom - nearly all flags disappear from the mod pane and the filetree for most (but not all) mods turns empty, as if MO is no longer able to properly interact with the VFS. If I try to interact with MO in any way at this point (for example, if I open up the details pane for a mod), it either crashes outright (sample crash dump attached), or I get the following series of errors - 

_failed to write log to /path/to/mo_interface.log: Insufficient system resources exist to complete the requested service._
_failed to write /path/to/mod/meta.ini: error 1_
_An error occurred trying to write back MO settings to /path/to/ModOrganizer.ini.new: File is write protected_

The MO directory is not write protected and I'm definitely not constrained by resources at the hardware level. Once I close and restart MO, all functions seem to work normally until the next time I play and exit FO4. Reproducible 100% of the time.

I am on Windows 10 and I am using MO in portable mode. I also tried using instance mode and ran into the same issues.

As a side note, this version of MO is also behaving strangely with F4SE for me. When I launch F4SE through MO, I get a popup stating that some component of F4SE has stopped working - however, I can click cancel on the popup and F4SE seems to initialize properly anyway (I can pull the F4SE version from game console and F4SE-reliant mods seem to work normally). Not really sure what's going on there.

Thanks.

[uvsfs_x64.zip](https://github.com/LePresidente/modorganizer/files/751530/uvsfs_x64.zip)

**Comment by dziemecki** [comment]
I wanted to add a "me too" to this bug to get a little more visibility.  I'm not having the F4SE issue, but the write error every single time are definitely causing me issues.

**Comment by NoICE** [comment]
#10 #50

**Comment by LePresidente** [comment]
Duplicate.
