### ISSUE TITLE
2.0.8.3 sort button

### ISSUE THREAD

**Issue by haileyambition** [LePresidente/modorganizer#55]
loot failed. Exit code was: 3221226356

running loot manually though as an external executable still seems to be working for me.

**Comment by Yoosk** [comment]
same goes for me, exact error

**Comment by Anach** [comment]
I get the same error with the sort button, but unfortunately, external LOOT and FO4Edit won't see any mods. They did initially, but at some point stopped working.

**Comment by haileyambition** [comment]
I still have to use the copy load order feature and manually edit the
loadorder and plugins files myself, run a bat file to remark plugins.txt,
but it works for me.  Try setting the loot exe to run as admin?

**Comment by Anach** [comment]
No luck with the run as admin.

**Comment by Anach** [comment]
> Try setting the loot exe to run as admin?

No luck running any/all of them as admin.

**Comment by haileyambition** [comment]
anach, maybe post your modorganizer.ini file?

**Comment by CrankyCat** [comment]
I have the same issue and I just installed both the current LOOT and MO 2.0.8.3. Initially the sort button worked but at some point I think there were too many mods.
