### ISSUE TITLE
VFS fails with external tools

### ISSUE THREAD

**Issue by Anach** [LePresidente/modorganizer#59]
All was working fine initially, and I had been using LOOT and FO4Edit without trouble. However, at some random point, they stopped working, and no longer see the VFS.

- LOOT only sees the plugins loaded from %LocalAppData%\Fallout4\Plugins.txt, which only lists the official plugins.
- FO4Edit also only sees the official plugins loaded from  %LocalAppData%\Fallout4\Plugins.txt. Even replacing the file with the MO Plugins.txt will result in FO4Edit saying the plugins do not exist and resetting the Plugins.txt
- BodySlide will not see any of it's template data installed through MO, and I am required to copy the files to the BodySlide folder manually, however, like the other tools, it will not see the VFS.
- Launching F4SE works fine with the VFS and the game sees all the mod data fine. This is what puzzles me.

I am using MO 2.0.8.3, on Win10x64. All Paths in settings are at default. I've tried numerous settings attempting to fix this, but had no luck.

*edit* Fixed bodyslide by adding it via the Data tab. Unfortunately this doesn't work with the other tools.

**Comment by haileyambition** [comment]
are you certain the paths settings are correctly pointing to the right folders where your mods physically are?

**Comment by Anach** [comment]
> are you certain the paths settings are correctly pointing to the right folders where your mods physically are?

Yes, as I said, the game sees the mods perfectly fine. Just LOOT and FO4Edit will not.

**Comment by haileyambition** [comment]
Have you tried deleting them and adding them as an executable fresh?

On Mar 5, 2017 3:58 PM, "Scott" <notifications@github.com> wrote:

are you certain the paths settings are correctly pointing to the right
folders where your mods physically are?

Yes, as I said, the game sees the mods perfectly fine. Just LOOT and
FO4Edit will not.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LePresidente/modorganizer/issues/59#issuecomment-284262124>,
or mute the thread

**Comment by Anach** [comment]
Yes, I have even retried setting up MO fresh, removing the entire appdata/MO folder. Bodyslide works, as stated above, but only when adding via the data tab, but this doesn't work for FO4Edit and Loot unfortunately, nor does adding the normal way. LOOT appears to be added by default on a new install, but even re-adding it doesn't allow it to see the VFS. 

I used MO v1 on Skyrim for years, and it worked very well. The occasional hiccup, but nothing that couldn't be sorted. 

I may try disabling a few mods and see if having a lower number of esp files helps, as suggested in another thread.

**Comment by Silarn** [comment]
I haven't encountered this issue. Can anyone verify that it exists on the dev builds?
