### ISSUE TITLE
Can't update MO2 + download with manager doesn't work

### ISSUE THREAD

**Issue by herdustisverypretty** [LePresidente/modorganizer#60]
There is a new version of MO2 on the SSE nexus (I have version 2.0.8.2 installed but 2.0.8.3b is available at this time), but MO says it is up to date already. 

The download with manager button on the Nexus site also does not work with MO2 anymore. Going into MO settings and clicking 'associate with download with manager links' doesn't change anything. I'm just told there is no application set up to handle the download.

**Comment by arkane149** [comment]
Mine started to do that, i reinstalled MO2 and it is currently working.

**Comment by arkane149** [comment]
Not working today.

**Comment by Silarn** [comment]
We can revisit this once normal releases are more regular again.
