### ISSUE TITLE
2.0.8.3b: Missing icuin54.dll?

### ISSUE THREAD

**Issue by Griffinhart** [LePresidente/modorganizer#61]
Downloaded and installed from the [releases/Beta 4.3](https://github.com/LePresidente/modorganizer/releases) link. Tried to run ModOrganizer.exe after installer finished, got the following error:

`The program can't start because icuin54.dll is missing from your computer. Try installing the program to fix this problem.`

I see a `ModOrganizer\DLLs\` directory and it contains a `icuin54.dll` - where should it be placed?

**Comment by rpsgc** [comment]
I just copied "icudt54.dll", "icuin54.dll" and "icuuc54.dll" from the "DLLs" folder to the root folder. That fixed the issue.

The alternative was to run MO as admin.
