### ISSUE TITLE
2.0.8.3 FO4 not recognising MO2 mods are loaded after updating LOOT and MO2

### ISSUE THREAD

**Issue by MyVeryUninteresting** [LePresidente/modorganizer#63]
After resolving a LOOT sorting issue (Same as seen in: https://github.com/LePresidente/modorganizer/issues/55) by uninstalling and reinstalling to the newest editions of both LOOT and MO2 (2.0.8.3), my saves all prompt with 'missing plugins' while in game and then crash to desktop if 'load anyway' is selected after a brief loading time.

The odd thing is the mods do appear to be loaded, during the loading screens prior to CTD textured, music, and otherwise modified files are present in their changes, but FO4 'thinks' that they are not.

I've tried the following things but still get the same in-game problem:

- Restoring backup modorders
- Reinstalling MO2 2.0.8.3
- Deleting MO appdata folder
- Removing MO2 2.0.8.3 and reinstalling to a new drive/folder
- Installing MO2 2.0.7
- Starting a new FO4 game (Still CTDs)

**Comment by MyVeryUninteresting** [comment]
Another reinstall with a fresh download of 2.0.8.3 appears to have fixed the issue. I am now prompted with an error of 'Failed to write mod list: failed to open temporary file', however the game/sort is functioning around this prompt.

**Comment by tryguy** [comment]
Oh, I think I get that error occasionally too. But, only when restarting the app over and over. Say, if I'm testing something, and starting skyrim to see it in game, over and over, maybe on the fifth or seventh time, it'll give me a message about something like it can't write to a file.

I ignore it and continue on. If I subsequently continue with testing, it'll present that notice each time, complaining about not being able to write or whatever.

But, I just need to exit MO2, and restart for that message to go away. I find I restart MO2 pretty often, just to avoid crashes and things not working. It is a lot better than it was though. This is on win 10.

**Comment by haileyambition** [comment]
I agree with tryguys flow, I have seen this pattern as well.

**Comment by nesho82** [comment]
yea i also use MO2 in that way

**Comment by CrankyCat** [comment]
Same issue as OP. Could this be related to the sort button no longer working and the number of mods? Does anyone have the sort button error and not have issues with mods not being present when FO starts?

**Comment by Superburns** [comment]
I think it might have something to do with the number of mods added. I ran into this problem as well, but reinstalling did not work for me. I did find out however that if i had 256 or more esp/esm files, (checked or unchecked) the game wouldn't recognize any of the mods that were placed (even the DLC). Hopefully this can be tested.

**Comment by Silarn** [comment]
I believe this is the memory issue which has been fixed for some time now. The mod limit is a hard limit of the game engine - however we should probably indicate this somehow. That's for a separate ticket.

**Comment by CrankyCat** [comment]
This happened to me with fewer than 200 mods.
