### ISSUE TITLE
Creation Kit hanging when it's closed

### ISSUE THREAD

**Issue by tryguy** [LePresidente/modorganizer#64]
So, I've begun to look into using the CK. And, I think it works well enough, but when shutting it down, the application doesn't close, it just hangs there.

It would be good if it closed cleanly. I'm not even sure if it writes files to the overload before it hangs, but I assume it does, since it closes the windows down until it's just the host window (hanging there). It'll be a while before I test if files are written, but I think it'd be good for the app to close cleanly anyway, rather than to force it closed each time. The original MO didn't have this issue. Or not when I used it.

**Comment by Rcj230** [comment]
A while back, the CK(32bit) would crash after about 15 minutes without fail. The fix(Kinda) was to disable the sound in the SkyrimEditor.ini file (bEnableAudio=0), did you try that fix? The ck will not crash, but you will have to "three finger salute" or pound the "X" key  till it closes. I do not quite remember if anything more was involved in the CK fix, but this is most likely not an MO issue. The 64bit CK works fine with MO.

**Comment by Silarn** [comment]
I haven't heard this issue from any testers recently. I'm going to close this.
