### ISSUE TITLE
2.0.8.3b Starting game through MO gives an error

### ISSUE THREAD

**Issue by ShadowySchemer** [LePresidente/modorganizer#67]
The error being: "Application load error 3:0000065432"
It might also be one of the mods I have, I'll do some more testing and get back to myself.

**Comment by ShadowySchemer** [comment]
Did some testing, none of my mods are the cause (which is the conclusion I came to when I launched a none-modded game via MO) I wish I knew what's causing this. I suppose I'll come back to it after there's been some updates on MO.

**Comment by sarf** [comment]
Usually that error is caused by some files not verifying according to Steam. Recommend re-verification, re-installation and sacrificing something valuable to your favourite Daedra.

**Comment by ShadowySchemer** [comment]
I'll try that, thanks. We shall see if Lord Sheogorath is in a good mood.

**Comment by ShadowySchemer** [comment]
Okay, I verified the game files (all was fine on that end) and re-installed it as well. It didn't work, however. I'm still getting the same error.

**Comment by cfs3rd** [comment]
Application load error P: 000000654321 and Error code 80
This is a synchronization issue with Steam.

1. The first thing to try is just to exit out of steam, not just close it from the x in top right corner, but in upper left click Steam>Exit. Restart Steam.

2. If that doesn't work then shut down the computer, not just restart but power off. Wait 2 minutes to allow the software hooks to reset or some such nonsense. Then restart.

3. Last is exit Steam again in the same way. Goto your Steam directory, for me it is here C:\Program Files (x86)\Steam and delete the clientregistry.blob file, if your Steam has it. Shut down the computer, not just restart but power off. Wait 2 minutes. Restart and Steam will create a new version of that file.

**Comment by ShadowySchemer** [comment]
I'll try that now, thanks.

**Comment by ShadowySchemer** [comment]
1 and 2 didn't work, and I can't find the clientregistry.blob file, so there's really nothing I can do about this, which saddens me so.

**Comment by ShadowySchemer** [comment]
But thank you, cfs3rd, I now know that it's a synchronization issue with Steam.

**Comment by ShadowySchemer** [comment]
Okay, I have narrowed the problem down to one program: F-Secure. When I have DeepGuard on, it completely prevents MO from launching the game, even though I would have MO on the list of allowable programs.

**Comment by ShadowySchemer** [comment]
Alright. I figured it out. There's this mode in F-Secure DeepGuard called "compatibility mode", when I enable that I can keep my AV on and not have that Steam error. Thanks to everyone who helped me, this trouble ticket can now be closed.
