### ISSUE TITLE
2.0.8.3: Avast putting MO in Virus Chest

### ISSUE THREAD

**Issue by Evolution0** [LePresidente/modorganizer#68]
OS: Windows 10 Pro x64

Normally this does not happen but under certain conditions (Which I have not locked down yet) Avast with put MO in the Virus Chest and even restoring + adding to exclusions does not restore it.

In my case it did this when I tabbed out of Fallout 4 and was browsing the Nexus for a mod I just remembered I needed, upon downloading it (via the manager link) I got this in my log:
```
17:48:42 [D] Download started
17:48:42 [D] download requested: nxm://Fallout4/mods/9407/files/77695
17:48:42 [D] add nxm download: nxm://Fallout4/mods/9407/files/77695
17:48:42 [W] QTcpSocketAPI: WinSock v2.0 initialization failed.
17:48:42 [W] QTcpSocketAPI: WinSock v2.0 initialization failed.
17:48:42 [W] QTcpSocketAPI: WinSock v2.0 initialization failed.
17:48:42 [W] QTcpSocketAPI: WinSock v2.0 initialization failed.
17:48:42 [C] request (http://nmm.nexusmods.com/fallout4/Files/77695/?game_id=1151) error: Unknown error (99)
17:48:42 [W] request failed: Unknown error
17:48:42 [D] Failed to request file info from nexus: Unknown error
17:51:03 [D] Download started
17:51:03 [D] download requested: nxm://Fallout4/mods/19063/files/77708
17:51:03 [D] add nxm download: nxm://Fallout4/mods/19063/files/77708
17:51:03 [W] QTcpSocketAPI: WinSock v2.0 initialization failed.
17:51:03 [C] request (http://nmm.nexusmods.com/fallout4/Files/77708/?game_id=1151) error: Host nmm.nexusmods.com not found (3)
```

I then thought it would probably be a good idea to close the game so I did that and tried another link but still no dice, I then decided to close MO and re-open it, upon attempting to do so I got the "This item does not exist do you want to delete the shortcut blah blah" message meaning.. MO was gone somehow.

I suspected Avast immediately and lo and behold after looking in the Virus Chest MO had been silently moved and quarantined.

Edit: Strangely enough I lost all permissions for the directory MO was installed to after this happened, it got locked as read-only no matter what I did, simply installing MO again elsewhere and copying everything over (as opposed to copying the exe over to the original) worked fine.

**Comment by gerbilOFdoom** [comment]
This is not an issue with MO - it's an issue with Avast.

**Comment by LePresidente** [comment]
Just add it to exclusions and send it as a false positive.

**Comment by LePresidente** [comment]
Closing this as this is not a MO issue.
