### ISSUE TITLE
2.08.1 force-loads uncheck plug-in after a LOOT sort

### ISSUE THREAD

**Issue by tjax323** [LePresidente/modorganizer#7]
It's not what I would call a serious issue, but for one very popular mod it can be. Helgen Reborn requires new save-games to be inactive. While testing other mods in prep for a play through, I noticed after sorting **and** applying the sort from LOOT, the plug-in is reactivated.

**Comment by Grogwort** [comment]
I can confirm and reproduce this behaviour launching LOOT through MO v2.0.8.1
Similar behaviour also occurs when launching Wrye Bash through MO
Disabled plugins are being re-enabled upon "return" to MO
Here are my testing steps:
LOOT
1. Disable one or more plugins in MO
2. Launch LOOT - Sort, Apply and close
3. Plugins order is updated properly, but disabled plugins are now re-enabled.

WRYE
1. Disable one or more plugins in MO
2. Launch Wrye Bash
3. Disabled plugins have moved to the bottom of sort order in Wrye file list
4. Update Bashed Patch or simply close Wrye Bash without doing anything further
5. Disabled plugins are now re-enabled, and at bottom of sort order

In each case, I am getting an error in the log after closing the external program and "return" to MO:
Failed to get process exit code: Error  5

**Comment by tjax323** [comment]
That's the exact same error code I receive.

**Comment by MaddBomber83** [comment]
That exit code pops up frequently for me.  Basically anytime running an external app (including Skyrim/SE) crashes.
