### ISSUE TITLE
USVFS is holding up Development

### ISSUE THREAD

**Issue by LePresidente** [LePresidente/modorganizer#71]
Currently usvfs won't compile the 32bit library required for 32bit apps to see the virtual filesystem on MSVC2015

To Reproduce:

1. check out latest modorganizer-umbrella (Master) from  "https://github.com/LePresidente/modorganizer-umbrella"
2. change archetecture to "x86" in config.py
3. start build using the following command "python unimake.py -d "F:/Build_32" usvfs"    (Change drive letter accordingly)

Ref to issue: https://github.com/TanninOne/usvfs/issues/1

**Comment by iaz3** [comment]
The build command fails, citing

> 2017-04-14 12:07:27,296 building dependency graph
2017-04-14 12:07:29,585 processing tasks
2017-04-14 12:07:29,591 run task "retrieve usvfs.git"
Cloning into 'C:\MO_Build_32\build\usvfs'...
fatal: Remote branch Dev not found in upstream origin
2017-04-14 12:07:30,323 failed to clone repository https://github.com/LePresidente/usvfs.git (returncode 128)
2017-04-14 12:07:30,323 task retrieve usvfs.git failed

(Previous tasks and dependencies completed)

**Comment by krisser143** [comment]
It looks like it tries to find an invalid branch called "Dev"

**Comment by iaz3** [comment]
Yes, obviously. It's still broken and doesnt build, and i cant find which file i need to fix to find the right branch.

**Comment by krisser143** [comment]
It just needs to point to the master branch. It looks for a branch called "Dev", which doesn't exist (i checked)

**Comment by iaz3** [comment]
Yes, obviously. I get that. Good job, captain obvious, you read the error and repeated it back to me.

The solution, obviously, is to find which file sets up the task and points to the branch. Except i cant find that file, and APPARENTLY github search doesnt work on forks, so i cant look for the line of code here >:(

I guess i'll have to just open every file and search manually.

**Comment by LePresidente** [comment]
Yea sorry was a dev branch i was messing with forgot it got pushed in a commit, reverted back to master.

**Comment by krisser143** [comment]
Fantastic, however what DOES the log say when compiling?

**Comment by krisser143** [comment]
Do you have an actual compilation log, so it's possible to see where the error occurs?

**Comment by iaz3** [comment]
Based on [this stackoverflow question](https://stackoverflow.com/questions/38463583/shared-memory-vectorstring-allocating-strings-with-8-byte-alignment-in-32-bit) and the linked patch, i've managed to get it to build.

Unsure how it will affect runtime code, my fix might break things.

[The patch](https://github.com/datastax/cpp-driver/pull/281/commits/4d82640fe19601679b732e9896704028d1e7f5bf) linked in the stackoverflow implements a thing for MSVC, and the boost type_traits file and the line specified by the compile log and add that patch, replacing `std::is_convertible` with `std::is_copy_constructible`

So what i did was go into

**Comment by LePresidente** [comment]
Ok let me implement that, i remember looking at the patch in the past trying something then getting the same error, shows my lack of experience. will give feedback shortly. thanks for the input

**Comment by iaz3** [comment]
Does mod organizer have a test suite or something to make sure it doesnt do nasty things?

**Comment by LePresidente** [comment]
usvfs does, just need to schedule the build on https://ci.appveyor.com/project/TanninOne/usvfs
