### ISSUE TITLE
Mod information tab is throwing errors when compiled with QT5.8

### ISSUE THREAD

**Issue by LePresidente** [LePresidente/modorganizer#73]
Due to qtwebkits getting the boot for qtwebengine, there are now issues where the mod information tab doesn't work and throws errors.

**Comment by willfe** [comment]
I'd be willing to look into this. I've got some experience with QT 4.x and 5.x on various platforms (including Windows) and might be able to shed light on the issue.

It might take me a day or two to get my development environment set up again for Windows development (it's been awhile :)) but if that's acceptable I'll get started on it after work tonight.

**Comment by LePresidente** [comment]
yea, sorry for the late reply been fixing umbrella. if you need any help regarding the environment let me know?

**Comment by willfe** [comment]
No worries! I should have posted a followup sooner.

I'm actually a bit stumped on how to set the environment up properly. I wasn't sure which repo(s) to actually clone locally to get the build started (as there are quite a few besides the main one). Is it just the "umbrella" repo that's needed, and it pulls the rest and builds automatically?

**Comment by LePresidente** [comment]
Yea, umbrella should do all the work, Use the WixDev branch though it is more up to date.

So for you to build you need VS2015 + VC common tools 
Python 64bit in your path

then run the following it will grab all the dependencies including QT and build them, catch me in discord if you have any issues

python unimake.py -d "E:/MO2"

change E: if you want to build somewhere else, though due to windows directory length don't make the destination to long.

**Comment by Silarn** [comment]
I don't believe this is still an issue?
