### ISSUE TITLE
Fallout 4 freezes after a minute when using F4SE through MO 2.0.8.3

### ISSUE THREAD

**Issue by malakengago** [LePresidente/modorganizer#74]
I apologize in advance that I know very little about coding and how programs truly work, but I hope the following information will show that I have attempted to fix my issue before thinking MO might be part of the problem.
My game will consistently freeze after about a minute or so once loaded in game if I use F4SE through MO.  I'm using only the Start Me Up mod.  When it freezes, alt + tabbing shows MO has unlocked by itself, and is sometimes accompanied by an error message, though the message is different if it does show up.  Seeing this, I also tried unlocking MO right after launching F4SE and then closing MO before then trying to load a game.  Freeze still occurs after about a minute.  I have already verified the game through Steam and I am using the latest drivers and versions of mods/programs.  I have also checked this against running F4SE normally with Start Me Up as the only active mod in NMM, and I experienced no freezing after several minutes and I was even able to start my character in Goodneighbor.  I have tried the workaround of using the script extender, though I was unsure if I still needed to try to start F4SE through MO after.  After though, I still experienced a freeze after about a minute.

**Comment by krisser143** [comment]
Does it randomly crash, or does it often happen when doing something specific (like opening a container, opening the pause menu, etc.)?
Have you tried without Start Me Up? If that doesn't work, could you perhaps try reinstalling MO if possible? Else it might be some setting in MO screwing you over.

**Comment by malakengago** [comment]
It's not random, I usually will just let it run for a bit before the game will freeze, and I'll be forced to end the process in task manager.  I have tried starting a new game without Start me up, but it still froze at the same point, usually during character creation or if I just selected default, soon after.  I did however discover that Start Me up doesn't seem to work well with mods that add perks right away to your character, and I had to activate that particular mod after loading into the actual game.  F4SE also still had trouble after a minute or so when I tried to start the game with my NMM install and then move on to MO.  I thank you for responding, but at this point, I've actually moved on to a full NMM install.  I knew the risk of using MO2 for Fallout 4, but I just like MO so much more than NMM that I thought I could deal.

**Comment by Silarn** [comment]
Can you verify this with latest builds? I don't recall any recent reports like this.

**Comment by malakengago** [comment]
I cannot verify with the latest build since I decided to move to NMM at the same time as my last comment.  I didn't have any further issues like what I experienced with MO, which was disappointing.  Since then, I have uninstalled Fallout 4 completely due to the whole creation club thing.  Still using MO for original Skyrim and New Vegas, which works great.
