### ISSUE TITLE
MO 2.0.7, LOOT Version 0.10.3 and Skyrim SE combo creates empty C:\program directory

### ISSUE THREAD

**Issue by frazmi** [LePresidente/modorganizer#75]
Running Skyrim SE current download from Steam
Mod Organizer is v2.0.7
LOOT is build 0fcf788b
My configuration: 
Windows 10, 32GB RAM, 1TB SSD, Intel i5-4460, GEForce GTX 760 w/2GB RAM (Driver v381.65)

**The problem:** I often see a new directory created: C:\program. I can delete it, but it keeps coming back.

The behavior is intermittent, however...
If I run Skyrim SE without MO, it never happens.
If I run MO alone, the directory is never created.
If I run LOOT alone, the directory is never created.

If the new directory is created, it's always when running LOOT from inside MO. Unfortunately, I have not been able to recreate a reliable step-by-step way to cause this fault to occur, but:

1.  It seems to happen only on the first load of MO. That is, if I delete C:\program, then the directory is not created again as long as I don't close MO.
2. If I run LOOT from MO but don't apply the results, the directory is not created.
3. If I run LOOT from MO and apply the results, the directory IS created most of the time (but not always). 

Creation of the directory sometimes does not happen until after I launch Skyrim (from inside MO). (I am not sure of this -- perhaps I just didn't notice the new directory.)
 
(Cross-posted from Tannin\ModOrganizer Forum)

**Comment by Shayown** [comment]
?

**Comment by krisser143** [comment]
I run loot too with MO, and I experience nothing like this. It might have something to do with your MO or loot setup. Try reinstalling loot (and MO if possible).

**Comment by frazmi** [comment]
I've reinstalled LOOT a couple of times. I just downloaded Mod.Organizer-2.0.8.2.exe. At first I could not install it -- the installer kept insisting that I did not have permissions needed. But on the third attempt, the installation completed. And so far the "Program" directory has not reappeared. THanks for the tip.
