### ISSUE TITLE
Crashes when opening windows browser

### ISSUE THREAD

**Issue by MaxMish** [LePresidente/modorganizer#76]
Whenever I try to load a mod or if I want to change Binary, as soon as the windows browser opens the app crashes. Every time. I tried to reinstall it, I tried to reinstall the Skyrim, I tried to delete every file that was related to NMM or Skyrim or Mod Organizer. It keeps crashing.

**Comment by Cheezyeggs** [comment]
I have this same issue, which completely prevents me from using the software.

Even within the MO interface, if I open a mod and try to view the files (still within the interface, not using explorer externally), it still crashes.
![internal mo file explorer crash](https://user-images.githubusercontent.com/30327106/32508752-8e5d0528-c3a8-11e7-8f3e-a1df67b83ada.png)
When this happens, the program becomes completely unresponsive, not even allowing me to create a log of the crash.

Trying to change the base Directory has the same effect.
![image](https://user-images.githubusercontent.com/30327106/32509055-790b5714-c3a9-11e7-9192-c1bda288ec50.png)
[usvfs-2017-11-07_17-52-21.log](https://github.com/LePresidente/modorganizer/files/1451082/usvfs-2017-11-07_17-52-21.log)

Note that it does not crash if the path is edited directly in MO, only on selection of the ellipsis (...).

**Comment by LePresidente** [comment]
Please join the discord server and test the build on the testers channel

**Comment by Cheezyeggs** [comment]
Latest Test Version crashes upon selection of Instance or Portable while inside program files.
Upon running it from a new folder outside of program files, it seems to have no issues.

I returned to the current release version and tested it outside of program files and it seems to have no issues. MO1 never gave me any problems running from within program files, so I didn't give it a second thought. Really was my mistake.

**Comment by Silarn** [comment]
It is probably being blocked as it was not 'installed' like the older versions. I'm going to close this.
