### ISSUE TITLE
ModOrganizer 2 crash due to running out of Memory after closing Fallout 4.

### ISSUE THREAD

**Issue by AikoTM** [LePresidente/modorganizer#80]
Everytime i close Fallout 4. No matter how.. even when it crashes - MO2 crashes aswell telling me it ran out of memory.

I have 16 GB of RAM which are perfectly fine. 
Search-function didnt yield any results when searching for the term 'memory'. So here i am.
Anybody know whats wrong?

**Comment by krisser143** [comment]
It's a normal bug. Once the application you are using through Mod Organizer reaches a specific threshold (requires you to at least load a game), will cause MO to have a lot of issues, including your error.
I think it's some memory management in MO that goes wrong, which possibly is a bug in usvfs.

These issues are possible dupes by the way, they are some of the exceptions that occurs when MO handles a program that reaches a specific memory threshold:
https://github.com/LePresidente/modorganizer/issues/50 and https://github.com/LePresidente/modorganizer/issues/45

**Comment by AikoTM** [comment]
Yeah i got #50 and #45 aswell sometimes when MO2 crashes after i close FO4.
Mind you i can still scroll through the Mod and Plugin list but as soon as i click on anything... crash.

**Comment by krisser143** [comment]
Exactly, MO becomes extremely fragile and unstable when you reach that ram threshold.

**Comment by LePresidente** [comment]
Will try look at this in the near future though time restraints my side are keeping me off this.

**Comment by NoICE** [comment]
I just found out the hard way that if you run into this (after 2 hours of playing Fallout 4), the game itself will start acting up. Loading screens will say "LOOKUP FAILED!" instead of the text, pressing Load from the menu will not find any saves. 

This already happened to me previously, but now, to make things worse, my (survival) EXITSAVE didn't happen. This is kinda serious :( I wish I could help you debug this, but I'm more of a Ruby/Go/Java/Kotlin dev. Building stuff for windows and hooking up to processes isn't my thing :/

What was the last MO2 version which didn't have this issue but still somehow works with Fallout 4? 2.0.8.1? or 2.0.8.0? Tried to find this info somewhere but I couldn't...

**Comment by dragonshardz** [comment]
Confirming that this issue is not present at all in 2.0.8.1. 2.0.8.2 and x.3 both exhibit this behavior, with .3 being measurably worse than x.2

I suppose the question then is which of the 26 changes between x.1 and x.2 introduced the bug.

**Comment by krisser143** [comment]
I could also (and most likely is) a change in vfs that made this happen, I will try to investigate once I get the time.

**Comment by krisser143** [comment]
This is most likely a bug in the vfs. Or it might be a bug in MO's use of said vfs. Both repos should have their commits checked because they are both equally a potential source of the problem.

**Comment by FireClaw** [comment]
I've had a similar issue after playing for a while as well. Here are some [screenshots ](http://imgur.com/a/1mZ4R) of the popups after it crashed if it helps.

**Comment by Silarn** [comment]
Long-standing memory crashes. Fixed on latest builds.

**Comment by dragonshardz** [comment]
What latest builds? Where? There hasn't been a commit to this repo in nearly a year and *your* MO forks are solely manual builds which I guarantee you people have no clue how to use.

**Comment by Silarn** [comment]
My forks are working branches which will be and have been merged here. All development builds are available on the Discord server linked on the main repo description.

**Comment by Silarn** [comment]
Just FYI https://github.com/LePresidente/modorganizer/tree/QT5.7 is the current working branch. At some point maybe @LePresidente will update master. But the [refactor](https://github.com/ModOrganizer/ModOrganizer) may be finished before then.
