### ISSUE TITLE
Cannot install FOMOD (Mod Configuration Menu) from archive. 

### ISSUE THREAD

**Issue by chanoc1** [LePresidente/modorganizer#81]
I am using Mod Organizer with Fallout New Vegas, and when I attempt to install a downloaded archive from Nexus Mods, which is in this case Mod Configuration Menu. For a second a blank dialouge comes up, but nothing gets installed, and no FOMOD menu is presented. 
```

18:36:12 [D] nexus category id 63 not mapped
18:36:12 [D] mod id guessed: The Mod Configuration Menu-42507-1-5.7z -> -1
18:36:12 [D] passed mod id: 42507, guessed id: -1
18:36:12 [D] using mod name "The Mod Configuration Menu" (id 42507) -> The Mod Configuration Menu-42507-1-5.7z
18:36:12 [D] not a simple archive
18:36:12 [D] simple expression matched, using name only
18:36:12 [D] passed mod id: 0, guessed id: -1
18:36:12 [D] using mod name "The Mod Configuration Menu" (id 0) -> C:/Users/diego/AppData/Local/Temp/The Mod Configuration Menu.fomod
18:36:12 [D] Opened  "C:/Users/[user]/AppData/Local/Temp/The Mod Configuration Menu.fomod"  using  "7z"  (from signature)

```

That is what appears in the log.

**Comment by LePresidente** [comment]
Currently there is no support for 32bit games till some c++ devs actually get onboard with this.

**Comment by chanoc1** [comment]
I see.

**Comment by chanoc1** [comment]
If anyone is going to respond, what is the difference between the old MO and this one? Isn't this just a continuation of Tannin's work? I don't see why 32 bit would stop working all of a sudden.

**Comment by LePresidente** [comment]
Yea though tannin made alterations to the usvfs library and well since there are no developers really working on this at the moment, for old 32bit games use 1.3.11

**Comment by LePresidente** [comment]
try the file I uploaded in https://github.com/LePresidente/modorganizer/issues/72, might work

**Comment by Silarn** [comment]
This duplicates #72 and was fixed with my recent NCC patch.
