### ISSUE TITLE
Loose files aren't being loaded when Fallout 4 launched via MO2

### ISSUE THREAD

**Issue by BaileyLove** [LePresidente/modorganizer#82]
I'm loosing my mind here.

I have 
```
bInvalidateOlderFiles=1
sResourceDataDirsFinal=
sInvalidationFile=
bUseArchives=1
```
in [Archive] section of every config (fallout4.ini, fallout4prefs.ini, fallout4custom.ini) everywhere (my games, mo2 profile folder, default configs in fo4 folder).

I've tried different versions of MO2. I've tried adding these lines into MO2 initweaks. I've tried the mo2 portable mode. 
Mo2, fallout4, instance folders are owned by my win10 user with full access.

But, it seems like no matter what, the loose files just won't be picked up by fallout4.exe if it's launched with mo2. I can see the esm's loaded in the fallout 4 mods menu. But not the loose files. I can place them in Fallout4/data and then fallout 4 sees them no problem. Also, the file structure in mo2's Data tab is perfectly correct.

What am I missing? Please help.

update: vfs log: 
[usvfs-2017-05-13_00-07-32.txt](https://github.com/LePresidente/modorganizer/files/998224/usvfs-2017-05-13_00-07-32.txt)

**Comment by LePresidente** [comment]
a bug with modorganizer2 and usvfs, there is currently an issue with the virtual path lengths where files are unreadable at a certain depth. Will need a c++ dev to fix though, I currently don't have the time.

**Comment by BaileyLove** [comment]
Oh, ok =D I'm gonna take a look then, but no guarantees. I have my hands full too. :(

**Comment by BaileyLove** [comment]
Umm... I'm afraid that's not the case. First I moved the instance into C:\\MO2FF4 and launched the game. No luck. Then I added Total Commander executable into mo2 and launched it with it and it's all there. All the loose files can be seen in total commander. So why fallout 4 exe won't pick'em up?

P.S. I've tried getting the sources to my pc, but the umbrella project just wouldn't do its thing. Also, it's usage synopsis is obscure and I don't have the time to hack through it all.

**Comment by haileyambition** [comment]
Want to agree with BaileyLove about pulling the umbrella, i have tried on multiple occasions to build this code to no avail.  Would love to help with the project but I also do not have the time to hack through building the whole thing.

**Comment by LePresidente** [comment]
I can't fix issue if there are no logs though,

To build umbrella this is crurrently the steps i following

1. Clone "https://github.com/LePresidente/modorganizer-umbrella"
2. Install Python 2.7.13 (x64) and add to path
3. Install Visual Studio 2015 Community + VC 2015 common tools
4. Install Windows 10 SDK (10.0.15063.0)  #Learnt this was a requirement for QT
5. Run unimake.py -d "F:\Build"

unimake will error a few times to tell you what is missing and needs to be added to the path or installed to the default location in program files.

**Comment by haileyambition** [comment]
"I can't fix issue if there are no logs though"
I complete agree LePresidente.  Tell you what, req #4 there is new to me so let me go at this again and get back to you with success or failure and/or logs.  Also, side note, I personally appreciate your adoption of this project and am in no way criticizing.

**Comment by BaileyLove** [comment]
LePresidente, what logs do you need? The ufs log is attached to the first post.

**Comment by Silarn** [comment]
This sounds like another issue we've got resolved in development builds. Grab them and test from the discord server.

I'm going to close this if we don't get a response in a few days.
