### ISSUE TITLE
conflict with current googletest while compiling usvfs in 32 bits

### ISSUE THREAD

**Issue by Hugues92** [LePresidente/modorganizer#84]
Sorry I couldn't create an issue in your USVFS repository.

Compiling the 32 bit version with the current googletest (c2d90bddc6a2a562ee7750c14351e9ca16a6a37a )
 generates an error:
D:\MO\1\build_32\googletest.git\googletest\include\gtest/internal/gtest-internal.h(893): error C2718: 'T1': actual parameter with requested alignment of 8 won't be aligned

Forcing googletest to use the latest release (branch ec44c6c1675c25b9827aacd08c02433cccde7780) resolves it.

Someone opened an issue for that on googletest I think: https://github.com/google/googletest/issues/1114

**Comment by LePresidente** [comment]
Fixed in umbrella. will check out release tag instead of master
