### ISSUE TITLE
2.0.8.3: Activates non-marked plugins in plugins.txt (FO4)

### ISSUE THREAD

**Issue by Freso** [LePresidente/modorganizer#87]
MO properly adds an asterisk in front of plugin files that should get loaded to `plugins.txt`, but instead of not marking other plugins in the file, it removes them completely (and adds them to `hide_plugins.txt`). If another program (e.g., LOOT) adds any unmarked plugins to this list, when MO next reads it it will treat those unmarked plugins and plugins that should be loaded and re-marks them.

**Comment by Silarn** [comment]
Unable to replicate this and I don't know of any recent reports of this behavior. You can probably get some support on our Discord channel.

**Comment by Silarn** [comment]
(BTW it sounds a bit like MO is interpreting your FO4 installation as a different game. But you'd be having other problems in that case as well.)
