### ISSUE TITLE
2.0.8.3: Running f4se_loader.exe makes it not load virtual file system

### ISSUE THREAD

**Issue by Freso** [LePresidente/modorganizer#88]
Running LOOT, FO4Edit, Creation Kit, vanilla `Fallout 4.exe`, etc. all load up the virtual file system perfectly, but when telling MO to run `f4se_loader.exe` it runs the game fine but doesn't see any of the plugins/files in the virtual Data\ folder.

**Comment by Freso** [comment]
I played around with a few different versions. It also doesn't work with 2.0.8 or 2.0.8.1, but it *does* work with 2.0.7. One of the things that changed from 2.0.7 to 2.0.8 is that 2.0.7 considers itself 64-bit and as such goes to `C:\Program Files` by default, while 2.0.8+ seem to consider themselves 32-bit and go to `C:\Program Files (x86)`. This is just speculation though.

**Comment by hex0id** [comment]
@Freso as a workaround I moved plugins directly to game Data folder, so they are visible to F4SE

**Comment by Silarn** [comment]
While I'm not sure I've ever seen it fail to load any mods, this sounds like it's probably due to the handle bugs. Please try the latest 2.1 build on the Discord server to see if it resolves your issues.

**Comment by Silarn** [comment]
Please respond to this ticket in the next several days or I will close it due to inactivity.
