### ISSUE TITLE
Problem with multiple instances

### ISSUE THREAD

**Issue by craig-t-tierney** [LePresidente/modorganizer#89]
I can't seem to have multiple instances working anymore. If I install Mod Organizer, and select Fallout 4, everything works fine, but if I install a separate instance of Mod Organizer that I want to use for New Vegas, that instance will work with my Fallout 4 settings and such, with the same happening if I try for Skyrim, Oblivion, or any other game. I'm sure that this is something wrong on my end, since as far as I cans ee I'm the only person to ever encounter this problem but I have no idea what and I've spent a few days fruitlessly trying to fix this.

**Comment by GSDFan** [comment]
The second "instance" needs to be run in portable mode.
Caution the following will reset MO to a first run state and some settings will be lost. The best way I have found to fix this is to shut down MO, go into your MO directory and rename ModOrganizer.ini to something else like ModOrganizer_old.ini. Start MO and you will see a dialog to select a game. Do not select a game, instead select the portable option. MO will restart and you will see all supported games that are installed in the next dialog, select your game from here.

**Comment by Silarn** [comment]
This is handled one of two ways. Either you use standalone mode and use the upper left button to change MO's current game - or you use multiple copies of MO in portable mode for different games.

There was an issue where automatic game detection could fail in portable mode, but a workaround was created for that issue until the autodetection can be corrected.

You may need to remove your ModOrganizer.ini to reset your instance and allow you to reselect the handled game.
