### ISSUE TITLE
x64 PDBs not available

### ISSUE THREAD

**Issue by fireundubh** [LePresidente/modorganizer#9]
I couldn't find, specifically, the `usvfs_x64.pdb` file in the PDB package. Can you add it?

I was hoping to get you more detailed information about an issue.

**Comment by ZachHaber** [comment]
I'm not sure why that wasn't included. When I built it recently, the usvfs_x64.pdb put itself into the pdb collection. Do you want me to get you the file?

**Comment by LePresidente** [comment]
Weird both the pdb's (X64 and X86) aren't  there, will add it now. sorry for the late reply festive season is always busy

**Comment by LePresidente** [comment]
Closing this as it has been sorted.
