### ISSUE TITLE
MO2 Crash when opening 'Fores New Idles in Skyrim' through MO2 that had recently closed

### ISSUE THREAD

**Issue by JamesYeoman** [LePresidente/modorganizer#92]
So I ran the "Fores New Idles in Skyrim"(FNIS) exe through MO2 (as per usual) and then realised that I had forgotten to check the FNIS dependent mods for male/female folders (for the gender-specific animations) so I closed FNIS, checked the mods and then went to launch FNIS again. Only, when I clicked on the toolbar shortcut, MO2 crashed.
[Here is the DMP file](https://github.com/LePresidente/modorganizer/files/1117150/ModOrganizerDumpFile.zip)

=====EDIT=====
It also crashes when any other external program is used after running FNIS. I tried to use the ESP/ESM Sort button and MO2 crashed. I then tested the theory by running FNIS and then SSEedit and it crashed aswell.

[ESP/ESM Sort Dump](https://github.com/LePresidente/modorganizer/files/1117156/ESP_ESM_SortCrashDump.zip) and [SSEedit Dump](https://github.com/LePresidente/modorganizer/files/1117157/SSEeditCrashDump.zip)

**Comment by Silarn** [comment]
This bug is caused by launching 32-bit applications alongside 64-bit games. However, this should be resolved on the current 2.1 builds. Please test the latest release on the discord channel to see if this fixes your issue.
