### ISSUE TITLE
Allow for a portable install? Problems with concurrent installations of MO and MO2

### ISSUE THREAD

**Issue by agentmith** [LePresidente/modorganizer#93]
I have Skyrim and FNV installed with a separate instance of MO for each, which works fine and I never had issues during setup or gameplay. I keep MO in the game folder, and everything MO-related within the MO folder itself. When I tried MO2 with FO4 it kept pulling settings and paths from FNV, and I could not get it to remember it's own unique settings, which subsequently broke FNV while MO2 was installed with mods and tools and such. It took me forever to figure out what the problem was, and after I uninstalled MO2 everything worked correctly again. 

Is there a way to get an install of MO2 going that stores it's settings local to the program folder, or in a way that won't pull information from other MO installations or games? I think it prompts for which game you want to manage when you load the program, and I'm not going to use it to manage anything other than FO4.

**Comment by Silarn** [comment]
I haven't heard any reports of this behavior from our testers. Can you please try with a recent build from the Discord server? If there's no response within the next several days I'm going to close the ticket due to inactivity.
