### ISSUE TITLE
When MO2 is launched through command line, F4SE doesn't load the vfs

### ISSUE THREAD

**Issue by azamorapl** [LePresidente/modorganizer#97]
If I launch MO2 and F4SE through the command line, the virtual file system is not loaded, and I can't see any mods. However, if I do it through the GUI, F4SE and the vfs load fine.

The same happens if I add Steam as an external executable in the GUI, but it's easier to test just by launching F4SE.

Example commands:
```
"ModOrganizer.exe" -p "Default" "F4SE"
"ModOrganizer.exe" -p "Default" "Steam" (given you have added an executable called Steam with -applaunch 377160 as arguments through the GUI)
```

I've skimmed through the logs and haven't figured out what the cause is. I see that I get the following message in mo_interface.log when I run it **succesfully** through the UI, not command line:

`[D] Failed to get process exit code: Error  6`

I've tried with ALL versions of MO2 and this issue is present. Also tried running as administrator and compatibility mode. This works fine in MO1.

Just a wild guess, but could it be because too many processes are spawned and MO can't hook itself to them?

I'm attaching success and failure logs:

[logs.zip](https://github.com/LePresidente/modorganizer/files/1254130/logs.zip)

**Comment by Silarn** [comment]
This sounds a bit like it's failing to call usvfs_proxy.exe - and I wonder if it's still present on the latest builds. I'll try to test this sometime soon.

**Comment by azamorapl** [comment]
I've just tested with the latest build from Discord and can confirm that this still happens.

**Comment by Silarn** [comment]
I believe this is related to the same problem as desktop shortcuts. This should be resolved on the latest builds.
