### ISSUE TITLE
Project built with Old Qt version - Qt5Declarative module non existent in latest Qt 5.9

### ISSUE THREAD

**Issue by Nik-Lz** [LePresidente/modorganizer#98]
Here is the complete error:

_CMake Error at src/CMakeLists.txt:234 (FIND_PACKAGE):
  By not providing "FindQt5Declarative.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Declarative", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Declarative"
  with any of the following names:

    Qt5DeclarativeConfig.cmake
    qt5declarative-config.cmake

  Add the installation prefix of "Qt5Declarative" to CMAKE_PREFIX_PATH or set
  "Qt5Declarative_DIR" to a directory containing one of the above files.  If
  "Qt5Declarative" provides a separate development package or SDK, be sure it
  has been installed._

I've asked about this on a Qt support forum and apparently Qt5Declarative has been removed since Qt 5.6. So what can i do to get through this and build this mod organizer project? I built it with `cmake CMakeLists.txt` on Windows 8.1 x86_64 with Qt 5.9 and cmake 3.7.2 and Visual Studio 2015 Community. Thanks in advance.

**Comment by LePresidente** [comment]
Ok i''m only going to support build failures with https://github.com/LePresidente/modorganizer-umbrella since thats what I use and I have a test environment to help with. 

If you want to go with your own builds please check the branches in https://github.com/LePresidente/modorganizer-umbrella/blob/master/makefile.uni.py

all the projects using the branch QT5.7 have been updated to at least compile with QTWebEngine.

**Comment by Nik-Lz** [comment]
Sorry, i made a mistake. I wanted to post this on TanninOne's same repository. I haven't checked yours yet. I'm sorry. Delete this thread if you want. I got confused.

**Comment by LePresidente** [comment]
No this is the correct place, as I was one of the few that got it to compile after tannin went to work for nexus and stopped working on MO.

Follow the instructions in  https://github.com/LePresidente/modorganizer-umbrella and it should compile

**Comment by Nik-Lz** [comment]
Ok. I too just learned that Tannin also quit working on MO and started working on NMM a few months ago. Well, i won't go back to NMM unless he makes it like MO. Anyway. So i posted this same thread on Tannin's same repository. I guess i shouldn't have right? Since Tannin is not working on this anymore, i should stop looking at his repositories and check yours only, correct? 

Alright i will check yours. I will start messing with them heavily since i'll finally finish uni very soon. I love MO. I think this program has great potential and it is the best of its kind i know of.

**Comment by LePresidente** [comment]
Yea, I don't have the c++ knowledge to fix this, Though I know enough about python and general coding to get it kinda compiling and making life easier for someone that wants to work on it properly. If you have any issues let me know

**Comment by Nik-Lz** [comment]
Ok. But what do you mean "fix this"? Is there a problem with the program, or you just wanted to say "to expand this program's features", or something like that? I have a fair amount of C++ knowledge.

**Comment by LePresidente** [comment]
There are few issues with MO2 and usvfs, it works just not bug free as tannin did leave it mid work.

https://github.com/LePresidente/modorganizer/issues/10
https://github.com/LePresidente/modorganizer/issues/50
