### ISSUE TITLE
Sort Button Doesn't Work!

### ISSUE THREAD

**Issue by SetArk** [LePresidente/modorganizer#99]
Hail!
This may be Old, but i'vent found anything aobut it.
Well, trying to use the Sort button, it tries to do lootcli.exe, but it stop working.
After, at M.O.2, there is an Error message saying.
loot failed. Exit code was: 3221226356.

So, this is what happens.
But opening Loot and sorting thorugh it, it works normally.
JUST DONT EVER TRY TO SORT WITH LOOT, AFTER TRYING WITH THE SORT BUTTON!
It messed up really good things here. Had to restart the pc.

**Comment by Luarst** [comment]
The sort button works fine for me. Have been using it often.

**Comment by NerouDesign** [comment]
The sortbutton only works with a few plugins. If it exceeds a certain number of plugins, it will crash. that's my experience.

**Comment by SetArk** [comment]
Welll, maybe it's about the number of plugins.
Tested with only 10 plugins in, and it worked.
Tested again with 160 plugins in, and loot crashed.

**Comment by Silarn** [comment]
What version of MO are you using? Issues with lootcli as well as ESL support have been resolved by recent development work. The next build should contain an updated LOOT API build which fixes a separate race condition in LOOT.

**Comment by SetArk** [comment]
Hail.
I'm using Mod Organizer 2.0.8.3
Revision: c64e12a

**Comment by NerouDesign** [comment]
same as setark. and its probably as you said Silarn, that the api is outdated.

**Comment by Silarn** [comment]
Integrated sorting is fixed in the development version. Closing this ticket.
